### ISSUE TITLE
Stable: Database Migrations for NDFD, NBM, Columbia River WRF

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#108]
- [x]  Merge cumulus-api `develop` --> `stable`
- [x] Database; Add New Acquirables
- [x] Database; Add New Products
- [x] Confirm Data is Posting and Processing

**Comment by brettpalmberg** [comment]
closes USACE/cumulus#105
closes USACE/cumulus#107

**Comment by adamscarberry** [comment]
products now processing in stable.  WRF Precip and Airtemp historic data bulk processed.
