### ISSUE TITLE
Product Descriptions

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#117]
### CBRFC MPE PRECIP 1hr
Source: https://www.cbrfc.noaa.gov/outgoing/usace_la/

Cumulus Description: 

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dui in augue porttitor dignissim. Vivamus laoreet, mauris id accumsan vestibulum, sem felis consectetur orci, nec aliquam massa turpis ac urna. Donec sodales ac dui vestibulum euismod. Morbi vulputate non tellus vel vehicula. Ut porta dolor odio, quis pellentesque sem semper id. Curabitur hendrerit sed diam elementum efficitur. Phasellus finibus, mi vel cursus tincidunt, augue mauris congue mi, nec ullamcorper tortor eros eget leo. Sed auctor ultricies tortor eu bibendum. Donec scelerisque consequat diam sed vehicula. Suspendisse interdum hendrerit velit vitae sagittis. Donec commodo sem in nunc cursus, nec interdum neque tincidunt. 
---
### HRRR PRECIP 1hr
Sources: 

1. https://noaa-hrrr-bdp-pds.s3.amazonaws.com (<-- using this source)
2. https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/

Cumulus Description:

> Product Description
---
### MBRFC KRF FCT AIRTEMP 1hr
Source: LDM

Cumulus Description:

> Product Description
---
### MBRFC KRF QPE PRECIP 1hr
Source: LDM

Cumulus Description:

> Product Description
---
### MBRFC KRF QPF PRECIP 6hr
Source: LDM

Cumulus Description:

> Product Description
---
### MRMS GAUGECORR QPE PRECIP 1hr
Source: Unsure, not currently acquiring, existing records from prev download
Records match format of: MRMS_GaugeCorr_QPE_01H_00.00_20200903-150000.tif

Cumulus Description:

> Product Description
---
### MRMS-V12 QPE Pass 1 PRECIP 1hr
Source: https://mrms.ncep.noaa.gov/data/2D

Cumulus Description:

> Product Description
---
### MRMS-V12 QPE Pass 2 PRECIP 1hr
Source: https://mrms.ncep.noaa.gov/data/2D

Cumulus Description:

> Product Description
---
### NAEFS MEAN QPF PRECIP 6hr
Source: LDM

Cumulus Description:

> Product Description
---
### NAEFS MEAN QTF AIRTEMP 6hr
Source: LDM

Cumulus Description:

> Product Description
---
### NBM AIRTEMP 1hr
Source: https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod/

Cumulus Description:

> Product Description
---
### NBM QPF PRECIP 1hr
Source: https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod/

Cumulus Description:

> Product Description
---
### NDFD AIRTEMP 1hr
Source: https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndfd/AR.conus

Cumulus Description:

> Product Description
---
### NDFD AIRTEMP 3hr
Source: https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndfd/AR.conus

Cumulus Description:

> Product Description
---
### NDFD AIRTEMP 6hr
Source: https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndfd/AR.conus

Cumulus Description:

> Product Description
---
### NDGD AIRTEMP 1hr (<--Legacy LTIA98)
Source: https://www.ncei.noaa.gov/data/national-digital-guidance-database/access

Cumulus Description:

> Product Description
---
### NDGD PRECIP 1hr (<--Legacy LEIA98)
Source: https://www.ncei.noaa.gov/data/national-digital-guidance-database/access

Cumulus Description:

> Product Description
---
### PRISM-EARLY PPT PRECIP 24hr
Source: ftp://prism.nacse.org/daily/tmin/YYYY/

Cumulus Description:

> Product Description
---
### PRISM-EARLY TMIN AIRTEMP 24hr
Source: ftp://prism.nacse.org/daily/tmin/YYYY/

Cumulus Description:

> Product Description
---
### PRISM-EARLY TMAX AIRTEMP 24hr
Source: ftp://prism.nacse.org/daily/tmin/YYYY/

Cumulus Description:

> Product Description
---
### RTMA-RU AIRTEMP 0hr
Source: https://nomads.ncep.noaa.gov/pub/data/nccf/com/rtma/prod/
Files matching rtma2p5_ru.t{HH}{MM}z.2dvaranl_ndfd.grb2 - Four times an hour - "00z", "15z", "30z", "45z"

Cumulus Description:

> Product Description
---
### SNODAS COLD CONTENT 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS-INTERPOLATED COLD CONTENT 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS SNOW DEPTH 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS-INTERPOLATED SNOW DEPTH 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS SNOW MELT 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS-INTERPOLATED SNOW MELT 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS SNOWTEMP 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS-INTERPOLATED SNOWTEMP 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS SWE 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### SNODAS-INTERPOLATED SWE 24hr
Source: ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/unmasked/

Cumulus Description:

> Product Description
---
### WPC QPF PRECIP 6hr
Source: https://ftp.wpc.ncep.noaa.gov/2p5km_qpf/
Cumulus Description:

> Product Description

**Comment by brettpalmberg** [comment]
Resetting status from "In Progress" --> "Todo" as this has been open for some time.

**Comment by willbreitkreutz** [comment]
Tabled due to being inactive.  @FHanbali if you get around to filling these out or need help, let us know.
