### ISSUE TITLE
[FEATURE REQUEST]: National Snow and Ice Data Center - SWE and Snow Depth

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#120]
## Feature Request Type
- [ ] ___User Interface (UI)___
- [ ] ___Application Programming Interface (API)___
- [x] New Product / Geoprocessor

## Is your feature request related to a problem? Please describe.
No issue related to this request.

## Describe the solution you'd like
Acquire daily 4 km snow water equivalent (SWE) and snow depth over the conterminous United States through the National Snow and Ice Data Center (NSIDC).  Create a processor transforming netCDF to COG.

- [x] Create GeoProcessor, test locally @jeffsuperglide 
- [x] Airflow DAG to notify Cumulus of files @jeffsuperglide  & @adamscarberry 
- [x] Deploy to Develop, process files @adamscarberry 
- [x] Deploy to Stable, process files @adamscarberry

**Comment by adamscarberry** [comment]
processed in stable 30-July-21
