### ISSUE TITLE
[BUG REPORT]: UI - Stale login allows user to initiate download

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#124]
- User closed browser and logged out of PC
- Upon PC login and browser launch, Cumulus login session appeared to still be active
- User tries to interact with web ui assuming they are still logged in
- Attempts to initiate a new download, but app finally discovers the user is not logged in (session timed out)
- User's download request is now in a black hole (technically an anonymous download which was not associated with the user's profile).
- User cannot see the download status.
- Manually logging out and back in resolved the issue

**Comment by willbreitkreutz** [comment]
I think we need to add a check in the init function of `create-keycloak-auth-bundle` that runs `selectTokenIsExpired` and if so runs a logout.  That way when the browser is refreshed we do a exp. check every time.
