### ISSUE TITLE
[FEATURE REQUEST]: Add Cold Content ATI and Meltrate State Grids

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#127]
CRREL's snow scripts used to generate these (default value) additional state grids, which the SNODAS model does not compute.   These state grids are needed to initialize HMS snow models.

**Comment by adamscarberry** [comment]
Reference for old grid processing script: https://github.com/CRREL/snowmelt

<img width="824" alt="image" src="https://user-images.githubusercontent.com/46494851/158257713-9a352b96-5a98-4d95-9917-7f8f747a51b7.png">

**Comment by brettpalmberg** [comment]
Zero grids were originally provided when previous versions of Hydrologic Modeling System (HEC-HMS) needed initial state grids, even if they are grids full of zeros. Newer versions of the modeling software can "Set Default Values" if grids are not provided. Zero grids will not be produced, stored, and served from Cumulus for the purpose of model initialization.
