### ISSUE TITLE
[BUG REPORT]: HRRR forecasts are way off, especially when compared to NDFD and WPC forecasts

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#128]
A good time frame to debug is the end of August through beginning of September forecasts over the Pennsylvania/New Jersey/New York area.  HRRR data was showing super low values (10^-3 or less) while the other forecast products were showing significant precipitation.

Suspect some kind of unit or conversion issue might be the culprit.

**Comment by jeffsuperglide** [comment]
Processor `band` number changed from 83 (Precipitation Rate [kg/m^2/s]) to 84 (Total Precipitation [kg/m^2]).  Band 84 defines the total precipitation for the band in the grib file, which is hourly.
