### ISSUE TITLE
SERFC and LMRFC QPE DSS records are coming out INST-VAL instead of PER-CUM

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#133]
SERFC and LMRFC downloaded QPE DSS records are being tagged as INST-VAL in the meta data, as well as missing the EPART (i.e. end of precip-cum duration) in the pathname part.

![image](https://user-images.githubusercontent.com/42588801/134255133-806277f4-b915-4b2c-ac76-2fa09f6b3860.png)

![image](https://user-images.githubusercontent.com/42588801/134255144-6a51f9f2-3a43-4425-b569-028b82fcc7d1.png)

**Comment by jeffsuperglide** [comment]
Temporal duration for SERFC and LMRFC updated to to period cumulative.
