### ISSUE TITLE
[BUG REPORT]: MBRFC 1hr temperature wrong Period Type

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#135]
The downloaded MBRFC 1hr temperature DSSrecords are coming out as PER-CUM with a D- and E-Part defined as well.  

![image](https://user-images.githubusercontent.com/42588801/135901317-743e3bd4-18e9-466e-92d4-3a81ad898558.png)

Should be INST-VAL with D-Part only.  The metadata header for the DSS record should also have the same Start Date/Time and End Date/Time.

**Comment by adamscarberry** [comment]
temporal duration in database was 3600 instead of 0.  Fixed via admin ui.
