### ISSUE TITLE
[API]: Download Metrics

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#137]
- [ ] Total number of downloads
- [ ] Downloads by Watershed/District

more capability TBD

**Comment by adamscarberry** [comment]
First pass:

![Screen Shot 2021-10-18 at 4 54 39 PM](https://user-images.githubusercontent.com/46494851/137805413-04523687-f628-4a5d-95d8-f9c6df3ad305.png)

**Comment by adamscarberry** [comment]
- Added local seed data for test during UI development/design.  
- Change endpoint from /downloads/metrics to /metrics/downloads to allow for future metrics

**Comment by adamscarberry** [comment]
initial view from the admin UI

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/46494851/157330193-356ec055-ae5d-424f-8209-4f0ab1026799.png">

**Comment by willbreitkreutz** [comment]
@adamscarberry I like it, that looks really good.

**Comment by adamscarberry** [comment]
initial implementation complete.  Can open another issue when more capabilities are needed.
