### ISSUE TITLE
[BUG REPORT]: Packager Fails (0 Files ) on WRF Downloads

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#151]
## Describe the bug

UI:

![image](https://user-images.githubusercontent.com/29417036/146847380-925e65fe-62d3-486f-84c2-3044d939a5d7.png)

Log:

![image](https://user-images.githubusercontent.com/29417036/146847536-b121ebfd-f6fe-4241-a057-f425fad15cb2.png)

**Comment by adamscarberry** [comment]
Resolved same day it was reported.  Forgot to close the issue.  WRF is observed data, but had forecast time set in database causing the query to result in no results.  Forecast time was set to the default value of 1111-11-11 to indicate not a forecast.  Confirmed download working.
