### ISSUE TITLE
[BUG REPORT]:  MBRFC-KRF-QPE missing values set to 9999 instead of 0.

### ISSUE THREAD

**Issue by Paul-R-Simon** [USACE/cumulus#152]
## Describe the bug
Outside of the clip extends is filling in missing values with 9999 instead of 0 for the z value.
## Steps To Reproduce
running script to pull grids from cumulus. 

## Expected behavior
I expected the missing grid cells to be set to zero.

## Actual behavior
missing values were filled in with 9999

## Screenshots
QPE has the issue
![image](https://user-images.githubusercontent.com/97703663/149415150-e5235deb-b58e-4ec6-ae28-c58054c98c9b.png)
 QPF looks good
![image](https://user-images.githubusercontent.com/97703663/149415158-b29ebfe5-7963-42dd-aac6-39150577270c.png)
throwing scale off in CAVI
![image](https://user-images.githubusercontent.com/97703663/149415150-e5235deb-b58e-4ec6-ae28-c58054c98c9b.png)

## Desktop (please complete the following information):
 windows 10
Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.70 GHz

## Additional context
thanks for the help

**Comment by adamscarberry** [comment]
@jeffsuperglide Related to https://github.com/USACE/cumulus/issues/130 ?

**Comment by jeffsuperglide** [comment]
packager.dss `noDataValue` should have fixed this.  👀  at packager.

**Comment by jeffsuperglide** [comment]
[USACE/cumulus-api/rsgis_dot_dev](https://github.com/USACE/cumulus-api/tree/rsgis_dot_dev) seems to have had its `packager.dss` module reverted back to a previous state before the `noDataValue` correction was made.  Solution would be to merge USACE/cumulus-api#192.  This PR also includes the slight refactor of MBRFC KRF QPE 01h meta data change to GRIB_REF_TIME and GRIB_VALID_TIME.

**Comment by jeffsuperglide** [comment]
USACE/cumulus-api#192 closes #152
