### ISSUE TITLE
[BUG REPORT]: Invalid JSX DOM attributes

### ISSUE THREAD

**Issue by willbreitkreutz** [USACE/cumulus#155]
## Describe the bug
Just noticed that there are a number of places where jsx has `class=` rather than `className=`

## Steps To Reproduce
1. Load the site in develop mode
2. Go to the docs page
3. Look at the console

## Expected behavior
No errors

## Actual behavior
Console error

## Fix
Do a find and replace for `class=` -> `className=` in all javascript files in `/src`

**Comment by brettpalmberg** [comment]
Good catch @willbreitkreutz!  Thanks for filing and we'll get this done.  I think @adamscarberry is polishing up some things in the UI as we speak.  @adamscarberry - may I assign this to you?

**Comment by adamscarberry** [comment]
fix should be pushing to develop now, thanks @willbreitkreutz  for the review!
