### ISSUE TITLE
Verify All Airflow DAGs Working

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#156]
- [x] DAGs retrieving data from websites starting w/ ftp:/ not working. @brettpalmberg 
- [x] High Resolution Rapid Refresh (HRRR) downloads are failing with HTTP Status 403

**Comment by brettpalmberg** [comment]
HRRR requests and associated DAG are. All S3 requests (s3.amazonaws.com) are routed through a VPC Endpoint. Configuration has been modified to allow required actions on bucket `noaa-hrrr-bdp-pds through VPC endpoint.  Confirmed working:
![image](https://user-images.githubusercontent.com/29417036/151045927-a068024b-1551-4fc9-96e7-5f75f403421f.png)

**Comment by brettpalmberg** [comment]
DAGs retrieving data via ftp:// are now working in the environment.

![image](https://user-images.githubusercontent.com/29417036/151053322-8d27637e-e473-4a62-b8f1-75d269cffecc.png)

**Comment by brettpalmberg** [comment]
All current Airflow DAGs should now work from this point forward in the environment. Root cause has been fixed, infrastructure-as-code updated.  Will open additional GH issues if we find any other DAGs that are not working.
cc: @willbreitkreutz @adamscarberry @jeffsuperglide

**Comment by adamscarberry** [comment]
awesome.  thanks @brettpalmberg !

**Comment by brettpalmberg** [comment]
You bet! Happy to jump in, team effort all the way through! 👍🏻
