### ISSUE TITLE
Research https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/offline.html

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#157]

**Comment by willbreitkreutz** [comment]
So, I think I figured this out, but I'm not sure if it's going to work for our use-case...   

What's actually happening is that the refresh token is the "offline" token, your access token is always set for the default access duration, using the offline option allows your application to get a new access token through the `refresh token` workflow and then go about it's business.  This might work but the script will need to be able to request that access token every time it runs.  

Offline tokens never expire, however you can make them single use, or revoke them at any time in the console.

**Comment by brettpalmberg** [comment]
Awesome!  Thanks @willbreitkreutz, I think this should work for the Cumulus use case.

Seems like we should extend `@usace/keycloak` and `@usace/create-keycloak-auth-bundle` to include method(s) for requesting offline tokens? Let me know what you think. I created a separate issue for this and assigned to you (hope that's alright, otherwise feel free to re-assign): USACE/usace-bundles#1

Looking ahead - @jeffsuperglide - this means that the relevant client script will need to be modified slightly. Before making any requests to the Cumulus API, the refresh token (the user-specific token that comes from the cumulus website) will be used to make a HTTPS request to the authentication server (keycloak).  This will return a payload that contains an `access token`. That `access token` will be what is used to interact w/ the Cumulus API. Everything else should be able to stay pretty much the same.

Closing this issue (research task), we can track implementation via other GH issues.

**Comment by jeffsuperglide** [comment]
@brettpalmberg - there may be more than a slight change.  Also have to consider HTTP2 and no support in jython/java 8.  The UI could still be rendered by jython but have Go interact w/ the API.  Jython could wait for that subprocess and then convert DSS6 to DSS7 as the last step.

**Comment by brettpalmberg** [comment]
> The UI could still be rendered by jython but have Go interact w/ the API

This seems like a good approach. Does `Go` already handle all of these API interactions, or is that in Jython at present?

**Comment by jeffsuperglide** [comment]
I have an update to `CaviTools` that has all the API interactions in `Go`.
