### ISSUE TITLE
[FEATURE REQUEST]: SNODAS Assimilation Layers

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#166]
## Feature Request Type
- [x] ***Application Programming Interface (API)***
- [x] ***Apache Airflow***

## New Product: SNODAS Assimilation Layers

Information provided on these products by others. Thank you for the background research!

> Daily tar files containing our assim layers can be found in [https://www.nohrsc.noaa.gov/pub/data/assim/](https://www.nohrsc.noaa.gov/pub/data/assim/). These include:
· the regional processing region vector outlines: "Assim_Processing_Region_${yesterday}_${today}_swe_${region}"
· the regional processing region raster masks: "ssm_process_region_${yesterday}_${today}_swe_${region}"
· the regional swe nudging field rasters: "ssm1054_${today}_${region}"
· and the mosaicked nudging field rasters: "ssm1054_${today}"
The vector outlines are going to be in our custom format, so likely less useful, but the mask or nudging field rasters should be usable enough as CF-compliant grids.

Recommend we start by adding a single product in cumulus, specifically: **the mosaicked nudging field rasters: "ssm1054_${today}"** This is a grid of +/- corrections applied to SNODAS Snow Water Equivalent results by lat/lon.

Data acquisition should be able to use Apache Airflow.

We can add other products from the .tar as needed in the future.

**Comment by adamscarberry** [comment]
@brettpalmberg In order to distinquish Corrections from SWE, suggest slightly different FPart.  Any suggestion besides `SNODAS-CORR`?

![image](https://user-images.githubusercontent.com/46494851/152629982-f4fedd8b-153b-49fe-809b-07daa2c2e1de.png)

**Comment by adamscarberry** [comment]
Will use the FPart `SNODAS-CORRECTIONS`.  Merged into develop

**Comment by brettpalmberg** [comment]
> Merged into develop

Nice work @adamscarberry !

**Comment by adamscarberry** [comment]
pydsstools reverted to 1.6 to fix packager.  Also handled condition where no grid coverage for a selected watershed extent.  UNDEFINED in the min/max/mean DSS stats results in the -3.4.... (aka no data) number.

**Comment by adamscarberry** [comment]
Waiting for review on DSS product from MVP.

**Comment by adamscarberry** [comment]
No further comments from district office.  Setting to complete/closed.
