### ISSUE TITLE
[BUG REPORT]: National Blend of Models Product Bands Not Consistent

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#170]
## Describe the bug
National Blend of Models products at https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod/ is showing grid band numbers not consistent between files.

The data source also seems to be inconsistent between forecast hours for 1 and 3 hour products.  A cycle hour may have hourly forecasts for hours 1-40, three hour forecasts 41-260, and be completely different the next cycle hour.

## Steps To Reproduce
1. Use GDAL grid info to view meta data
2. Find `"description": "0[-] SFC=\"Ground or water surface\""` and `"GRIB_COMMENT": "Temperature [C]"` in each grid info and compare the band number

## Expected behavior
Expected behavior would be consistency for products

## Actual behavior
inconsistent banding

## Additional context
`nbm-co-01h` requires modification to search for descriptions and `GRIB_COMMENT` in place of the band number.

**Comment by jeffsuperglide** [comment]
Additional thoughts...

The index (.idx) file defines the bands and the band's data.  Maybe index files should be downloaded with the grib file.

A couple index file example rows:

- `30:26281590:d=2022020411:APCP:surface:109-115 hour acc fcst:prob >0.254`
- `41:36430017:d=2022020411:APCP:surface:114-115 hour acc fcst:`
- `51:45959133:d=2022020411:TMP:surface:115 hour fcst:`

Each line in the index file provides the band, date, parameter, and interval can be inferred.

**Comment by jeffsuperglide** [comment]
USACE/cumulus-api#202 solves issue #170

**Comment by willbreitkreutz** [comment]
@jeffsuperglide can this issue be closed?

**Comment by jeffsuperglide** [comment]
@willbreitkreutz - PR USACE/cumulus-api#202 does close this issue and only applies the corps.cloud
