### ISSUE TITLE
[BUG REPORT]: Anon GET requests not going through, causing bundles to hang in loading state

### ISSUE THREAD

**Issue by willbreitkreutz** [USACE/cumulus#171]
## Describe the bug
Moving to the shared bundles changed a config key.  The `unless` key changed to `skipTokenConfig` in the new code.

**Comment by brettpalmberg** [comment]
Hey @willbreitkreutz - hoping we got this one fixed here. 
 https://github.com/USACE/cumulus/issues/174

**Comment by willbreitkreutz** [comment]
Need to push the fix to the usace-bundles repo, waiting on publish rights.

**Comment by willbreitkreutz** [comment]
usace-bundles has been updated, waiting on move to tailwindui to fix permanently.

**Comment by adamscarberry** [comment]
resolved, moved castle cloud to tailwindui March 2022
