### ISSUE TITLE
[FEATURE REQUEST]: Support Multiple Gridded Data Download Formats

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#176]
## Feature Request Type
- [ ] ***User Interface (UI)***
- [ ] ***Application Programming Interface (API)***

The async_packager currently supports downloads exclusively in DSS7 format using the library gyanz/pydsstools.

**Comment by brettpalmberg** [comment]
Slight refactor of the async_packager to support multiple output formats is complete.  A scaffold for the `tgz-cog` writer has been created: https://github.com/USACE/cumulus-api/blob/develop/async_packager/packager/writers/tgz_cog.py .  `tgz-cog` writer is not yet implemented.  @jeffsuperglide or @adamscarberry - one of you willing to take it from here?

**Comment by adamscarberry** [comment]
Note to whoever picks this up:
 ```
filename = f'{item["dss_fpart"]}_{item["dss_cpart"]}_{item["dss_dpart"]}_{item["dss_epart"]}.tif'        
        ds = gdal.Warp(
           f'/vsitar/{filename}',
           f'/vsis3_streaming/{item["bucket"]}/{item["key"]}',
```
`vsitar` cannot be used to write, only read.
https://gdal.org/user/virtual_file_systems.html#vsitar-tar-tgz-archives

**Comment by brettpalmberg** [comment]
@jeffsuperglide to implement extensible plugin system for writers as part of pyplugs refactor.

**Comment by brettpalmberg** [comment]
Resetting to "wontfix" at this time, as this capability is not being requested/prioritized by any stakeholders. Can be re-opened in the future if necessary.

**Comment by brettpalmberg** [comment]
Working on this here: [176-feature-request-support-multiple-gridded-data-download-formats](https://github.com/USACE/cumulus-api/tree/176-feature-request-support-multiple-gridded-data-download-formats)
