### ISSUE TITLE
[FEATURE]: Drop cumulus-ui 'xhr' dependency from package.json

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#181]
After changes are published to npm (see USACE/usace-bundles#6, USACE/usace-bundles#8), cumulus-ui should be able to update to the latest version of `@usace/create-jwt-api-bundle` and drop `xhr` as a direct dependency in cumulus-ui/package.json

**Comment by willbreitkreutz** [comment]
usace bundles have been published, I've switched the tailwindui branch to use the new version and will do some testing there.  once we move to tailwindui this will be fixed

**Comment by adamscarberry** [comment]
new tailwindui was deployed to stable a couple weeks ago
