### ISSUE TITLE
[BUG REPORT]:missing data areas are being filled in with 9999.0 values

### ISSUE THREAD

**Issue by Paul-R-Simon** [USACE/cumulus#190]
## Describe the bug
the IaMOOsage grids are filling in the missing values around the perimeter of the clip with 9999 values instead of zero.

![image](https://user-images.githubusercontent.com/97703663/159509985-cb3f3915-41a6-4fd5-85d6-b37413f00605.png)
![image](https://user-images.githubusercontent.com/97703663/159510070-a445c513-6ee2-4838-8ac6-d06c0f30bc26.png)

**Comment by adamscarberry** [comment]
this was resolved in castle cloud stable
