### ISSUE TITLE
[FEATURE REQUEST]: Strategy to version geoprocessors

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#208]
## Feature Request Type
- [ ] ***GeoProcessor***

## Is your feature request related to a problem? Please describe.
When a product changes formats/structures, the existing processor may not work.  In order to re-process the data for the time period when it did work, we don't want to change the processor for only new files (and lose ability to handle older versions).

## Describe the solution you'd like
Consider a strategy to version processors and have logic to detect the processor needed or based on a date range.

## Other thoughts
We discussed just creating new products, but consider down the road we have MRMS v12, MRMS v13, etc and products spread across all these multiple versions.  This will make deciding which product to download for a specific time period difficult for users.

**Comment by willbreitkreutz** [comment]
We don't have a method for storing the required metadata for associating a processor to a date-range etc... This is a good idea and should be implemented at some point especially if we need to back-process data.  Tabling for now until we run into a need.
