### ISSUE TITLE
[BUG REPORT]: UI Download % Complete doesn't update properly

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#212]
During a download, the % complete only seems to update immediately or after an APP_IDLE action has been dispatched.

Bug seems to be around https://github.com/USACE/cumulus-ui/blob/43e38a1de0d6dff08f668061b0203e8913c912d4/src/app-bundles/download-bundle.js#L64

**Comment by brettpalmberg** [comment]
@adamscarberry , working on this now.
