### ISSUE TITLE
[Metrics] Setup Monitoring

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#214]
## Prometheus
- [x] Managed AWS Prometheus Setup
  - [x] Terraform config, deployment

## Grafana
- [x] Docker image setup, workflow deployment
- [x] Terraform config, deployment
  - [x] Keycloak integration
- [x] sigv4 authentication settings 

## Keycloak
- [x] Integration for Grafana auth

## Cumulus Exporter
- [x] postgres exporter image setup, workflow deployment
- [x] Terraform config, deployment
- [ ] metrics user with approp roles
  **Consider more elevated role for metrics collection in the future if provided metrics are insufficient**

## Cumulus API Endpoint (existing Go API)
- https://github.com/USACE/cumulus/issues/218

## Prometheus Scraper
Required to scrape metrics and push metrics to Managed Prometheus Service in AWS. Managed prometheus service accepts POST of metrics, does not scrape.
- [x] Create container repositories @brettpalmberg 
- [x] Images and Github Actions deployments @adamscarberry 
    - [x] cwbi-prometheus
    - [x] cwbi-prometheus-sidecar
- [x] Notes
    - [x] Set a short period of storage for metrics in cwbi-prometheus container so ephemeral container storage does not fill up.
    - [x] sigv4 authentication settings
- [x] ECS Task Definition and Infrastructure as Code Deployment @brettpalmberg

**Comment by brettpalmberg** [comment]
@adamscarberry and @brettpalmberg added **Prometheus Scraper** section to this issue just now.

**Comment by brettpalmberg** [comment]
Saving some notes while they're fresh in my mind. Can we review the following settings before we close this out?
- [ ] Scrape interval for Prometheus
- [ ] Default interval for Grafana
- [ ] Stable deployment
