### ISSUE TITLE
[BUG REPORT]: Airflow Storage Growth in Container at `/opt/airflow`

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#216]

**Comment by adamscarberry** [comment]
New DAG deployed (not enabled yet).  @brettpalmberg can you remove the env var for base_log_folder?  This should put logs back into /opt/airflow/logs and the new DAG will purge files older than 2 days in that log dir.

**Comment by brettpalmberg** [comment]
> can you remove the env var for base_log_folder?

Done ✅ You should find this environment variable has been removed for both `develop` and `stable` instances.

**Comment by adamscarberry** [comment]
thanks @brettpalmberg.  Will verify this is working properly tomorrow or early next week.  Then we can close issue.

**Comment by adamscarberry** [comment]
verified it's working, but may need to take a different approach for new configuration with separate worker(s).  Leaving open to revisit after we get the bugs out of new configuration.

**Comment by brettpalmberg** [comment]
Now that we've moved from Airflow LocalExecutor ==> CeleryExecutor, we will probably need to implement a sidecar container to cleanup logs on each individual container now that there are multiple worker containers.

**Comment by brettpalmberg** [comment]
I'm thinking we do something simple like this in a sidecar container that shares the volume holding log files with the Airflow containers, followed by a `sleep` in a `while true` loop: https://unix.stackexchange.com/questions/194863/delete-files-older-than-x-days

**Comment by adamscarberry** [comment]
Can all worker containers share the same logs volume? If so, could we have a single cleanup container?

**Comment by brettpalmberg** [comment]
Hey @adamscarberry.  I think each worker container will have its own separate volume, but each worker will mount their own volume at the same path (/opt/logs?).  Then, we can share that volume with a sidecar container. Each worker will have its own sidecar container, though they will each be identical. Sidecar will handle `rm -... /opt/logs` style command.

**Comment by willbreitkreutz** [comment]
Closing until we run into the issue again.
