### ISSUE TITLE
[FEATURE REQUEST]: Enable Prometheus Middleware for Go Echo API

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#218]
## Feature Request Type
- [ ] ***User Interface (UI)***
- [X] ***Application Programming Interface (API)***

## Additional context
This will provide additional visibility into real-time usage metrics by URL route, support anomaly detection, and early detection of issues.

**Comment by adamscarberry** [comment]
Deployed to to `develop`

**Comment by adamscarberry** [comment]
Hey @brettpalmberg, can you add a new env var to our self managed prometheus instance called `$CUMULUS_API_METRICS_TARGETS` ?  It should point to the internal API host on port 9090.  Thanks!

Once ready, I'll commit the change for the prometheus to scrape that endpoint.

**Comment by brettpalmberg** [comment]
> 

@adamscarberry, change has been applied.

**Comment by brettpalmberg** [comment]
Needed to make another fix. It should be working now, for real this time :).  We needed to make some changes to how we were attaching/structuring security groups because we had reached the maximum number of security groups that can be attached to the service api (Cloud Service Provider limit is 5).
