### ISSUE TITLE
[FEATURE REQUEST]: Add StatsD Exporter for Airflow --> Prometheus

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#221]
# Details

- [x] Add Python dependency to Airflow image: `pip install 'apache-airflow[statsd]'` ✅ https://github.com/USACE/airflow-config/commit/d2bb7b2e8633049fc6c4dbe4d63fae4ae62be634
- [x] Add environment variables to Airflow services
    - [x] Scheduler
    - [x] Webserver
    - [x] Worker
```# METRICS
    AIRFLOW__METRICS__STATSD_ON: True
    AIRFLOW__METRICS__STATSD_HOST: airflow-statsd-exporter
    AIRFLOW__METRICS__STATSD_PORT: 9125
    AIRFLOW__METRICS__STATSD_PREFIX: airflow
```
- [x] Add environment variable to Prometheus Sidecar (airflow-statsd-exporter.localvpc)
    https://github.com/USACE/castle-cloud-metrics/blob/develop/docker-compose.yml#L23
- [x] Add repository for airflow statsd exporter
- [x] Add statsd service
- [x] Github workflows for airflow-statsd-exporter

# Deployments
- [x] Develop Environment
- [x] Stable Environment

# References

- Airflow docs: https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html

**Comment by brettpalmberg** [comment]
Initial configuration complete. Monitoring services to confirm everything is working and we can adjust settings as necessary.

**Comment by brettpalmberg** [comment]
This appears to be working as designed per review of `develop-` grafana instance and newly available metrics.  @adamscarberry, when convenient, can you confirm that everything looks good from your vantage point?  If so, thinking we can deploy to the `stable` environment and close the task.

**Comment by adamscarberry** [comment]
Thanks @brettpalmberg for setting this up.

Unfortunately, I'm not seeing all the expected metrics.

Examples:

- dag_file_refresh_error
- scheduler.tasks.running
- scheduler_heartbeat
- executor.running_tasks

There are many more missing, these were just examples of missing metrics we would like to use.

**Comment by adamscarberry** [comment]
correct, looks like all the dag and task instance (ti) metrics are available.

**Comment by brettpalmberg** [comment]
All metrics are sending now after bouncing Airflow containers (I bet bouncing the scheduler was the key piece to start generating the missing metrics). Perhaps the scheduler was last deployed before the statsD service was online and it gave up trying to communicate with statsD after a while.  Mind checking everything from your side @adamscarberry to make sure everything is there now?

**Comment by adamscarberry** [comment]
awesome!  Looks good now.

**Comment by brettpalmberg** [comment]
> [x] Stable Environment

**Comment by adamscarberry** [comment]
This appears done to me.  Closing...
