### ISSUE TITLE
[BUG REPORT]: Misc async_packager Fixes

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#224]
## Describe the bug

* Packager container crashing, related to asyncio and httpx
* Limits in DSS range table missing range to show beyond null values

## Expected behavior

Container running in stable condition without crashes

**Comment by jeffsuperglide** [comment]
USACE/cumulus-api/pull/#304
USACE/cumulus-api/pull/#305

Closes this issue.
