### ISSUE TITLE
[FEATURE REQUEST]: Sphinx Documentation for Packager, Geoprocess

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#225]

**Comment by brettpalmberg** [comment]
@adamscarberry , can you please take a look at the Sphinx docs (review)?

**Comment by jeffsuperglide** [comment]
Sphinx documentation moved to Mkdocs.  Sphinx and jekyll not playing well together with the current docs setup for components of cumulus-api.  YAML and Markdown bases for documentation configuration.  Geoprocess and Packager documentation pages updated with Mkdocs.
