### ISSUE TITLE
[BUG REPORT]: DSS Downloads for MRMS Precipitation

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#226]
## Describe the bug

All grid values in downloaded DSS file are 0.

**Comment by brettpalmberg** [comment]
Status Update:  This is affecting additional data products in addition to MRMS

The issue has been isolated to the process that clips/warps grids for download, isolated to the options passed to `gdalwarp` for a subset of products.  Good news, we think the stored archive of files is unaffected and should not require re-processing, it's a packaging issue "on the way out".  @jeffsuperglide is hot on the trail to fixing this 👍🏻 🚀.

**Comment by adamscarberry** [comment]
This should be resolved with latest PR (https://github.com/USACE/cumulus-api/pull/316)

MRMS Example:
![image](https://user-images.githubusercontent.com/46494851/177664166-9b181e40-c34f-4599-b97d-be726b75e1cd.png)

**Comment by ktarbet** [comment]
@brettpalmberg @jeffsuperglide  @adamscarberry 

Update on what @sharkcooper @ktarbet  have learned looking at this issue.

The DSS7 grid we thought was all zeros, appears instead to be all  -3.4028235E38 (GRID_NODATA_VALUE)
When reading DSS7 the three statistics from disk are zeros.

When converting the grid to DSS6 the statistics are recomputed before saving to disk.
in-memory Statistics include:  maxDataValue=-2.0E38, _minDataValue=+2.0E38, meanDataValue=GRID_NODATA_VALUE

save to disk happens (may be more steps to explore tomorrow)

read back in DSS6 the three statistics each become  -Infinity   (not sure why yet, we can explore tomorrow)

**Comment by brettpalmberg** [comment]
@ktarbet, @sharkcooper, thank you guys for digging into this.  Based on the symptoms you observed in the sample file, I'm wondering if the issue is in the way we are writing DSS7 Precipitation Records, specifically what is set as their `._nullValue` in the spatialGridStruct.

I think [Line 146](https://github.com/USACE/cumulus-api/blob/stable/async_packager/src/cumulus_packager/writers/dss7.py#L146) sets any `nodata` cells in the grid array of value to 0 for precipitation grids in almost all cases. This part should be ok.

I am suspicious of [Line 147](https://github.com/USACE/cumulus-api/blob/stable/async_packager/src/cumulus_packager/writers/dss7.py#L147) and the use of `nodata = 0` used later in [Lines 177-178](https://github.com/USACE/cumulus-api/blob/stable/async_packager/src/cumulus_packager/writers/dss7.py#L177-L178). Does `spatialGridStruct._nullValue = c_float(0)` sound right?

**Comment by ktarbet** [comment]
@brettpalmberg -  I can see what you mean, that for a precipitation grid, a zero could be a surrogate for missing -- the drawback is we would not be able to differentiate between missing and zero.

I'm interested in investigating how the statistics, and range tables are written.  From my test file with all missing, It appears the stats may be initialized with zero instead of a _nullValue. 

@jeffsuperglide --  should I be looking in C code for the stats computation?
Specifically here are the 'statistics' I'm thinking about:

```
_maxDataValue
_minDataValue
_meanDataValue
_rangeLimitTable -- array
_numberEqualOrExceedingRangeLimit -- array

**Comment by jeffsuperglide** [comment]
Stats and range limits computed in C (tiffdss).  Min, Max and Mean functions using foat *data, int datasize and float nodata to compute ignoring no data values.

**Comment by brettpalmberg** [comment]
^ @ktarbet

**Comment by ktarbet** [comment]
Thanks @jeffsuperglide and @brettpalmberg for pointing out that code.

I like the look of tiffdss.c

How about we set up a test that begins with a tiff and ends with a DSS6 file , and prints message about what is wrong if anything.   This would help 1) define the problem, 2) provide future test case(s) that prevents regression.   

The test would run tiffdss.c with a input precip tiff, then run a simple Java program to convert from DSS6 -> DSS7.   It could all run in Linux to make is easier with gdal requirements.   How can I help?

As far as problem definition the only Issue I've seen is a file with all missing data that had stats indicating min=0, max=0 which seemed misleading.  (attached, but I don't have a test to reproduce )

[grid-with-zeros.zip](https://github.com/USACE/cumulus/files/9075198/grid-with-zeros.zip)

**Comment by jeffsuperglide** [comment]
@ktarbet - `tiffdss` source in the `cumulus-api` repo can be compiled for command line execution for a single tiff.

**Comment by FHanbali** [comment]
@ktarbet I just noticed that gageinterp seems to write out -infinity values for interpolated grids that are supposed to be all zero values.

Here are configuration and scripts files to help test.  Let me know if you'd like to connect and see how to run through the CAVI for any of the class watersheds.  But I think it's worth checking on the gageinterp source code to see which DSS library and methods might be the culprits.

  
[gageinterp.zip](https://github.com/USACE/cumulus/files/9078357/gageinterp.zip)

**Comment by ktarbet** [comment]
@FHanbali are you reporting a new issue, or or you suggesting gageinterp may be the source of this issue (#226) ?
