### ISSUE TITLE
[FEATURE REQUEST]: Allow Log Visibility for Monitoring

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#227]
## Feature Request Type

Intentionally keeping details vague :). Make logs visible in monitoring solution for the following services:

- [x] async_packager
- [x] async_geoprocess

# Details

- [x] Permissions policy (@brettpalmberg)
- [ ] Dashboard Configuration (@adamscarberry)

**Comment by brettpalmberg** [comment]
Log read permissions should now be allowed to the Grafana dashboard for async_packager and async_geoprocess cloudwatch logs. Let me know if they're not showing up for any reason. Re-assinging to @adamscarberry for Grafana implementation.

**Comment by adamscarberry** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/46494851/184702092-e0298a5e-3828-4c0a-9d39-adb98840bda9.png">

Same query in console:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/46494851/184702207-873cc9dd-3848-4a8a-b775-f778cfd2fae9.png">

**Comment by adamscarberry** [comment]
Thinking a permission for log insights might be needed.

**Comment by brettpalmberg** [comment]
Thanks @adamscarberry. Will take a look.

**Comment by brettpalmberg** [comment]
Hey @adamscarberry, I noticed the screen-capture above is looking at the API cloudwatch log /ecs/develop-cumulus/**api**. Is it working for either the ...**/packager** or ...**/geoprocess** log groups?  I did not allow grafana read access on the **/api** log group (but we can if necessary).

**Comment by adamscarberry** [comment]
negative: 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/46494851/184875417-8b39c6ed-3543-476d-86d5-346477de432e.png">

**Comment by willbreitkreutz** [comment]
Table in lieu of a bigger monitoring scope as we move to production.
