### ISSUE TITLE
[FEATURE REQUEST]: Host MVP Gridded DSS Archives on Cumulus

### ISSUE THREAD

**Issue by msweier** [USACE/cumulus#228]
## Feature Request Type
- [ ] Add to Cumulus archives

## Is your feature request related to a problem? Please describe.
Would like to use Cumulus as a one stop shop for MVP gridded data services. 

## Describe the solution you'd like
Move MVP archive data to Cumulus and discontinue reliance on T7 servers.

## Describe alternatives you've considered
Mirroring Cumulus real-time data and adding to MVP archives on T7.

## Additional context
Link to MVP gridded archives.
https://wm.mvp.ds.usace.army.mil/Data.html

**Comment by brettpalmberg** [comment]
Good Morning @msweier!  Thanks for taking the time to create a Github Issue for this! Let's connect on this next week with a few other folks on the team and put a plan together.

cc @adamscarberry @jeffsuperglide @FHanbali

**Comment by brettpalmberg** [comment]
@msweier, are the original format grids (grib, xmrg, etc.) available, or only the post-processed DSS archive?  Can you remind me what the original source format for the grids? 
 Apologies, I can't get to the internal link from my current machine / network connection (should be able to get to it on Tuesday).

**Comment by msweier** [comment]
@brettpalmberg, we just have the post-processed DSS archives on our server. Cumulus has most of the data, but we have some data going back a bit further.  It looks like you guys have the pretty much all the airtemp data (or something similar), but we would like the SNODAS data extended back for it's period of record and observed, calibrated, 1-hr, rainfall grids ([Stage IV data](https://data.eol.ucar.edu/dataset/21.093)) to go back to at least 2008. Thanks!

**Comment by brettpalmberg** [comment]
Thanks @msweier, great information! If we downloaded and processed all of the data from the Stage IV link you shared, would that meet the intent of uploading the St. Paul District NCRFC Stage 4 data? It appears that the Stage IV archive for CONUS extends the following date ranges per their information:

Begin datetime | 2001-12-31 12:00:01
-- | --
End datetime | 2022-05-31 23:00:00

It is unclear to me how this data may differ from the realtime Stage IV Grids provided by NCRFC. Do you know if it is the same or has significant differences?

**Comment by msweier** [comment]
@brettpalmberg yes, the Stage IV data should be a mosaic of all the RFC produced data. It's my understanding that once an individual RFC issues a QA/QC'd observed rainfall grid, this product is called Stage III. Stage IV includes all the data from the other RFCs....not sure how they deal with differences near the boundaries, but it should be good enough for our use.

**Comment by brettpalmberg** [comment]
Hey @msweier, sharing a note that we're going to be working on the Stage IV Mosaic dataset here: #255. Thank you for sharing this information.

**Comment by msweier** [comment]
Thanks Brett! Looking forward to the update!

From: Brett Palmberg ***@***.***>
Sent: Wednesday, August 3, 2022 4:53 PM
To: USACE/cumulus ***@***.***>
Cc: Weier, Mitchell S CIV USARMY CEMVP (USA) ***@***.***>; Mention ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [USACE/cumulus] [FEATURE REQUEST]: Host MVP Gridded DSS Archives on Cumulus (Issue #228)


Hey @msweier<Blockedhttps://github.com/msweier>, sharing a note that we're going to be working on the Stage IV Mosaic dataset here: #255<Blockedhttps://github.com/USACE/cumulus/issues/255>. Thank you for sharing this information.

**Comment by brettpalmberg** [comment]
@msweier, would like to track this work under #255 and close this issue for now. Let me know if this misses any of the requirements documented here and we can absolutely open it back up. Thanks so much for sharing all the relevant information here. Stay tuned!
