### ISSUE TITLE
[FEATURE REQUEST]: Products to Support MVS CWMS Operations

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#230]
### Additional Data Products Available via Cumulus

- [x] NAEFS Grids processing (current outage) (@adamscarberry investigating)
- [ ] Future: Full watershed Stage IV Precipitation for Mississippi River Extent (Extends NCRFC and LMRFC extents)

### Bugfixes
- [x] DSS7 --> DSS6 Conversion Issue on CAVI Script Download

**Comment by brettpalmberg** [comment]
> DSS7 --> DSS6 Conversion Issue on CAVI Script Download

In progress.  Additional discussion in #226

**Comment by adamscarberry** [comment]
NAEFS Grids  - No forecast received for 3 days (as of 7/7/22 @ 8pm).  Will need @jeffsuperglide to investigate LDM, ensure product has not been renamed by source (or some other anomaly).

**Comment by adamscarberry** [comment]
NAEFS outage seems to have resolved itself.

cc @jeffsuperglide

**Comment by brettpalmberg** [comment]
👍🏻 Closing this issue.
