### ISSUE TITLE
[BUG REPORT]: Packager error

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#241]
Found issue based on user's failed download.  No further details.  Needs research.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/46494851/182384289-fde39d58-a882-42c4-baa1-485f1f811e38.png">

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/46494851/182384370-a00a09a0-6074-46ae-a3db-e75d38b2a5f3.png">

**Comment by jeffsuperglide** [comment]
First thought is VSI file reference may have released before gdal.unlink().  May need a try...except.

**Comment by adamscarberry** [comment]
again:  

![image](https://user-images.githubusercontent.com/46494851/184361945-8c9c176a-5cb5-4bf2-b28b-2b620e10e071.png)

cc @jeffsuperglide  @brettpalmberg

**Comment by jeffsuperglide** [comment]
Updates in `cumulus-api` branch `feature/tiffdss-rangetable-stats` may solve this issue.  Try...Except added to `gdal.Unlink` with logger.info to see error.

**Comment by brettpalmberg** [comment]
I wonder if this may a factor too. https://gdal.org/api/python_gotchas.html#python-crashes-if-you-use-an-object-after-deleting-an-object-it-has-a-relationship-with

**Comment by adamscarberry** [comment]
@jeffsuperglide  @brettpalmberg 

Do we have a fix waiting in develop to be merged into stable for this?

![image](https://user-images.githubusercontent.com/46494851/186513571-4ef022b2-82b6-4ac2-a7b1-a05d6afb9321.png)


![image](https://user-images.githubusercontent.com/46494851/186513460-8db36bfb-5dc5-4cc8-b1f1-3e90de207689.png)

**Comment by brettpalmberg** [comment]
@adamscarberry, I'll tee something up for merge today.

**Comment by adamscarberry** [comment]
@brettpalmberg thanks.  There could be something odd about this product (mbrfc...) that causes the failure while others don't.

**Comment by brettpalmberg** [comment]
> @adamscarberry, I'll tee something up for merge today.

Nothing yet today, will pick this up again another time. The `.delete()` method may be the right option in this case since we're using `/vsimem/` (https://github.com/OSGeo/gdal/issues/2337).

**Comment by adamscarberry** [comment]
closing this issue as packager has a refactor several months ago
