### ISSUE TITLE
[PRODUCT]: SNODAS:  2004-2010

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#244]
SNODAS: 2004-2010 raw grids and compute interpolated version

ftp://sidads.colorado.edu/DATASETS/NOAA/G02158/legacy

**Comment by jeffsuperglide** [comment]
Backloading DAG for Airflow merged into USACE/airflow-config develop.  Geo-processor updated to handle SNODAS files from 2004 - 2010.  Testing to continue on develop-cumulus.corps.cloud.

**Comment by brettpalmberg** [comment]
Nice @jeffsuperglide! Good work!  Setting-up a Draft PR from `develop` --> `stable` pending confirmation of manual testing.  USACE/cumulus-api#330

**Comment by brettpalmberg** [comment]
@adamscarberry, can you put this through a few QA paces in `develop`?

- [ ] Test results look ok in `develop`
- [ ] Merge to stable

**Comment by adamscarberry** [comment]
@brettpalmberg  Trying to acquire file with airflow, but they are either slow or failing.  Either source server is struggling or I'm being rate limited.  Will try again in the morning.

**Comment by brettpalmberg** [comment]
👍🏻 Sounds good. Thanks @adamscarberry.

**Comment by adamscarberry** [comment]
@jeffsuperglide `SNODAS SNOWTEMP 24hr` has no data for the test period of Jan 2004.  Does this sound right?  Do we expect it to come and go?

cc @brettpalmberg

**Comment by brettpalmberg** [comment]
That sounds right. I think 2004 is touch and go for SNODAS data, but 2005 should be solid coverage if I remember correctly.

**Comment by adamscarberry** [comment]
`SNOW MELT` has records as 0500 while `SNOW MELT INTERPOLATED` has records as 0600

![image](https://user-images.githubusercontent.com/46494851/183644126-6226f15b-a014-45fc-b8c2-7ca1ca21db75.png)

**Comment by jeffsuperglide** [comment]
I know exactly why that is.

interpolate.py line 178

**Comment by brettpalmberg** [comment]
@adamscarberry, @jeffsuperglide, 0600 is the correct timestamp for SNODAS (0500 is incorrect). Here is a note from the SNODAS documentation on NSIDC: https://nsidc.org/sites/default/files/nsidc_special_report_11.pdf

> Example: us_ssmv11034tS__T0001TTNATS2003102305HP001.grz is modeled snow
water equivalent (ssmv11034) summed for all the layers of the snow model (tS__). It is
the output from just one hour (T0001), representing the time step starting at 2003-10-23
0500h (TS2003102305), is potentially generated for every hour of the day (H) and
represents the snow an hour after the start of the time step (P001). E.g. SWE at 0600h

We will want to check if this is impacting current realtime processing for SNODAS as well.

**Comment by adamscarberry** [comment]
Not sure if it should have, but many of the interpolated products visually fill the missing holes.  In the image above, `snow melt interpolated` looks the same as original `snomelt` record.

**Comment by adamscarberry** [comment]
**Cold Content** Sample output from develop:

![image](https://user-images.githubusercontent.com/46494851/183775974-114bf1ab-501c-47ec-8664-aa16e88de934.png)

**Snow Depth** sample output from develop

![image](https://user-images.githubusercontent.com/46494851/183776225-70a9ba7d-65f8-4153-9f32-5e95524cbbcc.png)

**Comment by adamscarberry** [comment]
@jeffsuperglide  and @brettpalmberg, if you don't see any issues with the above sample from develop (Jan 2006), the snodas backload dag is in stable turned off (set to run for WY2004 at the moment...of course can be adjusted for whole period.)

**Comment by jeffsuperglide** [comment]
https://github.com/USACE/cumulus-api/blob/ca44c1b3017e68de9fdbfadcdb56b7c2ece642b8/async_geoprocess/src/cumulus_geoproc/geoprocess/snodas/interpolate.py#L169-L174

**Comment by adamscarberry** [comment]
Backload of 2004 - 2010 in progress...

**Comment by adamscarberry** [comment]
Backload done.

Masked = 2004 - 16Feb2010
Unmasked = 17Feb2010 - present

SWE visual example:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/46494851/184379916-dca4bec3-a1cd-420d-be9a-a3f5323fcfa4.png">

**Comment by adamscarberry** [comment]
complete
