### ISSUE TITLE
[PRODUCT]: NERFC QPE

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#245]
## Product Source (URL Preferred)

Currently, this product is acquired by local office via LDM `REQUEST ANY (nerfc2coe.qpe)(.*)(.grb)`

Grids not available via HTTP at this link at time of this GH Issue: https://tgftp.nws.noaa.gov/data/rfc/nerfc/

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [ ] NetCDF
- [ ] Other (Please provide description below)

**Comment by brettpalmberg** [comment]
Update: QPE grids now appear to be available at the link in the initial issue https://tgftp.nws.noaa.gov/data/rfc/nerfc/

cc @adamscarberry @jeffsuperglide

**Comment by adamscarberry** [comment]
Meant to PR this, but acidently pushed straight to airflow develop.

https://github.com/USACE/airflow-config/commit/9fd159082ec2eefda6be3e2b90d870895dece64d

NERFC QPE Dag Done ✅

**Comment by brettpalmberg** [comment]
Geoprocessor added to USACE/cumulus-geoproc in this PR: USACE/cumulus-geoproc#26

**Comment by brettpalmberg** [comment]
Data acquisition enabled in Airflow for develop & stable instances of service; Closing issue.
