### ISSUE TITLE
[PRODUCT]: NERFC QPF

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#246]
## Product Source (URL Preferred)

Currently this product is acquired by local office via LDM `REQUEST ANY "nerfc.qpf"`

Grids **not available via HTTP** at this link at time of this GH Issue: https://tgftp.nws.noaa.gov/data/rfc/nerfc/

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [ ] NetCDF
- [ ] Other (Please provide description below)

**Comment by brettpalmberg** [comment]
Update: Grids are still not available via HTTP at this link at time of this message: https://tgftp.nws.noaa.gov/data/rfc/nerfc/

**Comment by willbreitkreutz** [comment]
Grids are still not available, tabling for now.
