### ISSUE TITLE
[PRODUCT]: CNRFC QPE 

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#248]
## Product Source (URL Preferred)

URL Structure: https://www.cnrfc.noaa.gov/archive/YYYY/MMM/netcdfqpe/qpe.YYYYMMdd_HHMM.nc.gz
Past 24 hours (ending 12 UTC) uploaded between 6-8 AM Pacific

Additional Information: https://cnrfc.noaa.gov/documents/CNRFC_Archive_Download_Instructions.pdf

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [x] NetCDF
- [ ] Other (Please provide description below)

**Comment by adamscarberry** [comment]
working on airflow now

**Comment by adamscarberry** [comment]
@brettpalmberg Looks like they have a significant archive back to 2003.  How far back should we load?

**Comment by brettpalmberg** [comment]
@adamscarberry, good find. I think we should ultimately load the entire archive back to 2003 if we are able. Thinking we start with the real-time data acquisition/processing to confirm everything works as intended. Then circle-back to process the entire archive after confirming results. Want to avoid having to re-process the entire archive if we find we need to adjust the geoprocessing after a few days.

**Comment by adamscarberry** [comment]
Airflow branch with new product: https://github.com/USACE/airflow-config/tree/feature/cnrfc-qpe-06h

Cumulus-API branch with new product: https://github.com/USACE/cumulus-api/tree/feature/cnrfc-qpe-06h

@jeffsuperglide Ready for you to add processor.

**Comment by jeffsuperglide** [comment]
CNRFC QPE gdalinfo for the Raster Band describes `projectionType` as `Polar Stereographic`.  Other oddity is the units are `inches`.

**Comment by brettpalmberg** [comment]
@timbbaldwin, do you have guidance on how we should approach the Polar Stereographic CRS on this product?

cc @jeffsuperglide

**Comment by adamscarberry** [comment]
Assuming this is results with no data in the grids:

![image](https://user-images.githubusercontent.com/46494851/184649311-6fa41cb2-3ed5-4346-b546-54c2e283323d.png)

Same results as mrms-pass2 and ndgd-rtma

**Comment by adamscarberry** [comment]
Tried another test with SPA - Rio Grande.  Same issue with CNRFC QPE, but MRMS and NDGD-RTMA showed data properly (likely because there was precip).

**Comment by jeffsuperglide** [comment]
`tiffdss` needs some attention.  Probably some work on `filter_nodata` function needs to be a bit smarter.

**Comment by adamscarberry** [comment]
QPE is in inches, migration needs fixed by @adamscarberry

**Comment by adamscarberry** [comment]
QPE DSS results based on CNRFC extents: 

![image](https://user-images.githubusercontent.com/46494851/208517661-67a557b6-0e77-4e88-bfc4-9842b05fcf9a.png)

**Comment by adamscarberry** [comment]
Comparison between CNRFC QPE and NCEP Stage 4 QPE:

![image](https://user-images.githubusercontent.com/46494851/208529951-982e02d6-a568-4245-8dda-78e0cc076abc.png)

Projection/warping is kinda funky

**Comment by brettpalmberg** [comment]
> Projection/warping is kinda funky

It sure is. Thanks for sharing the side-by-side comparison @adamscarberry.

Grids from CNRFC reference a Polar Stereographic coordinate reference system (CRS). The CRS is not specified in the source files in a manner that can be recognized by [GDAL utilities](https://gdal.org/index.html).

We implemented a coordinate reference system (CRS) approach in USACE/cumulus-geoproc that assigns the geotransform and projection to the grid file to the best of our knowledge so it can be recognized by GDAL. This would benefit from coordination and review from the data provider (CNRFC) on the approach we applied.

**Comment by jeffsuperglide** [comment]
From CNRFC

> FOR QPF:
 
# until Jul 1st, 2010 and after Sep 7th, 2011.

# x scalar: 4762.5 * 0 = 0
# y scalar: 4762.5 * -250 = -1,190,625
crs.hrap.QPF.1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"

# Jul 2nd, 2010 through Sep 6th, 2011

# x scalar: 4762.5 * 127 = 604,837.5
# y scalar: 4762.5 * -202 = -962,025
crs.hrap.QPF.2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2509837.5 +y_0=6657975 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For Forecast Temperatures:
 
crs.hrap.QTF.1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For Observed Temperatures:
 
# before 10/1/2020
 
crs.hrap.TOBS.1  <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2466975 +y_0=6534150 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
# 10/1/2020 to present
 
crs.hrap.TOBS.2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For QPE:
 
# 6/3/2002 through 9/30/2020 12Z
 
crs.hrap.QPE1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2466975 +y_0=6534150 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
# Starting 9/30/2020 18Z to present
 
crs.hrap.QPE2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2202656.25 +y_0=6515100 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
