### ISSUE TITLE
[PRODUCT]: CNRFC QPF

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#249]
## Product Source (URL Preferred)

URL Structure: https://www.cnrfc.noaa.gov/archive/YYYY/MMM/netcdfqpf/qpf.YYYYMMdd_HHMM.nc.gz

Updated 1x/day summer and 2x/day winter except 1x/day weekends/holidays

Additional Information: https://cnrfc.noaa.gov/documents/CNRFC_Archive_Download_Instructions.pdf

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [x] NetCDF
- [ ] Other (Please provide description below)

**Comment by adamscarberry** [comment]
@brettpalmberg My concern with going back and forth between 1x/day and 2x/day is the temporal duration.  That needs to be fixed to one value for the packager to write the DSS with proper times.

Winter has 1200 and 1800 while summer only has 1200.  Other than only doing 1200 year round, you have any other ideas?

Can't remember if DSS grids can handle irregular times.  If that's needed, we'll have to modify our big wall of sql (https://github.com/USACE/cumulus-api/blob/stable/sql/common/R__05_views_downloads.sql) to accommodate it

**Comment by adamscarberry** [comment]
Fun note, https://www.cnrfc.noaa.gov is currently down this morning.

**Comment by brettpalmberg** [comment]
> Fun note, https://www.cnrfc.noaa.gov/ is currently down this morning.

This spurred an idea for how we could pretty simply create a "down detector" for each product. I'll start to lay-out some technical requirements and create a Github Issue. This is important, as we're adding a lot of new products. Need the visibility. cc @FHanbali

**Comment by adamscarberry** [comment]
Since this is an odd ball with different products during summer/winter, here's my approach:

1. Attempt a download for 1200 UTC and 1800 UTC products every day
2. If 1800 and (months are May - Sep OR weekend day), failed attempt will be skipped (not retried)
3. Otherwise 1200 and 1800 attempts will be retried multiple times before failing

Example of airflow runs where 1800 attempts are skipped (pink) after initial fail:
![image](https://user-images.githubusercontent.com/46494851/182917898-352be3d3-ea6c-4a53-a5ee-62486bd8401e.png)

**Comment by brettpalmberg** [comment]
> Example of airflow runs where 1800 attempts are skipped (pink) after initial fail

@adamscarberry, the graph in this case is what would typically be expected on Weekends or during the Summer months. Correct?

**Comment by adamscarberry** [comment]
@brettpalmberg Correct, weekends or Summer months

**Comment by adamscarberry** [comment]
I accidentally added this new dag into the same branch with ncrfc-qpe-06h.  Should be ok.  Just for awareness.

Airflow Branch: https://github.com/USACE/airflow-config/tree/feature/cnrfc-qpe-06h

Cumulus-API branch: https://github.com/USACE/cumulus-api/tree/feature/cnrfc-qpf-06h

Ready for processor @jeffsuperglide

**Comment by brettpalmberg** [comment]
> 

Issue added for a simple endpoint showing product ingest status. 
https://github.com/USACE/cumulus/issues/258

**Comment by adamscarberry** [comment]
Example qpf filepath: https://www.cnrfc.noaa.gov/archive/2022/Dec/netcdfqpf/qpf.20221201_1200.nc.gz

**Comment by adamscarberry** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/46494851/206571334-d3524264-450f-4a25-ab44-ca4bc6a3f522.png">




<img width="300" alt="image" src="https://user-images.githubusercontent.com/46494851/206571035-d4c2856a-4685-4582-a7ca-9a7edac9f87f.png">

**Comment by adamscarberry** [comment]
QPF is in inches, migration needs fixed by @adamscarberry

**Comment by brettpalmberg** [comment]
Grids from CNRFC reference a Polar Stereographic coordinate reference system (CRS). The CRS is not specified in the source files in a manner that can be recognized by [GDAL utilities](https://gdal.org/index.html).

We implemented a coordinate reference system (CRS) approach in USACE/cumulus-geoproc that assigns the geotransform and projection to the grid file to the best of our knowledge so it can be recognized by GDAL. This would benefit from coordination and review from the data provider (CNRFC) on the approach.

Data acquisition and processing is enabled in develop & stable versions of the cumulus app. A tag was added to the CNRFC products "BETA Testing" to inform users that this product is still under testing/verification. Closing issue now.

cc @FHanbali @adamscarberry @jeffsuperglide

**Comment by jeffsuperglide** [comment]
From CNRFC

> FOR QPF:
 
# until Jul 1st, 2010 and after Sep 7th, 2011.

# x scalar: 4762.5 * 0 = 0
# y scalar: 4762.5 * -250 = -1,190,625
crs.hrap.QPF.1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"

# Jul 2nd, 2010 through Sep 6th, 2011

# x scalar: 4762.5 * 127 = 604,837.5
# y scalar: 4762.5 * -202 = -962,025
crs.hrap.QPF.2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2509837.5 +y_0=6657975 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For Forecast Temperatures:
 
crs.hrap.QTF.1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For Observed Temperatures:
 
# before 10/1/2020
 
crs.hrap.TOBS.1  <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2466975 +y_0=6534150 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
# 10/1/2020 to present
 
crs.hrap.TOBS.2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=1905000 +y_0=6429375 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
For QPE:
 
# 6/3/2002 through 9/30/2020 12Z
 
crs.hrap.QPE1 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2466975 +y_0=6534150 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
 
# Starting 9/30/2020 18Z to present
 
crs.hrap.QPE2 <- "+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k=1 +x_0=2202656.25 +y_0=6515100 +a=6371200 +b=6371200 +to_meter=4762.5 +no_defs"
