### ISSUE TITLE
[PRODUCT]: CNRFC NBM QTF

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#251]
## Product Source (URL Preferred)

URL Structure: https://www.cnrfc.noaa.gov/archive/YYYY/MMM/netcdfFcstTemp/fcstTemperature.YYYYMMdd_HHMM.nc.gz

01/07/13/19Z runs of NBM, updated within about 1.5 hours of model time

Additional Information: https://cnrfc.noaa.gov/documents/CNRFC_Archive_Download_Instructions.pdf

Additional information from email:

> The NBM data is also available via NOMADS https://nomads.ncep.noaa.gov in GRIB2 format, and you’re already grabbing NBM data (just not sure about your source).  Either way, we need to version the data sources appropriately.  The nice thing about the CNFRC NBM data is that they reprocess the 3- and 6-hourly portions of the forecast and combine into a single hourly dataset.  For your reference, here are differences between the NOMADS and the CNRFC NBM datasets:

  | NOMADS | CNRFC
-- | -- | --
Spatial Resolution | 2.5 km | 4.7 km
Temporal Resolution for temps | Hourly, 3-hourly, 6-hourly | Hourly
Issuance | Issued hourly, but forecast length varies from 18 hours to 10-11 days | Every six hours, always with at least 10 days of forecast length
Format | GRIB2 | NetCDF
 
**Addition Information from Recent Email**

> NBM QTF (hourly):
General Link: https://www.cnrfc.noaa.gov/archive/YYYY/MMM/netcdfFcstTemp/fcstTemperature.YYYYMMdd_HHMM.nc.gz
Example link: https://www.cnrfc.noaa.gov/archive/2022/Aug/netcdfFcstTemp/fcstTemperature.20220822_0700.nc.gz
Index:  https://www.cnrfc.noaa.gov/arc_search.php?product=netcdfFcstTemp
Comment: Availability is at 0000, 0700, 1200, 1900. This is slightly different than the expected 01/07/13/19Z.
Comment 2: Hourly data, issued every 6 hours, NetCDF, 4.7 km resolution. This was preferred to the NOMADS data; tradeoff of hourly timescale vs. spatial resolution.

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [x] NetCDF
- [ ] Other (Please provide description below)

**Comment by brettpalmberg** [comment]
Updated issue description with section `Addition Information from Recent Email`

**Comment by brettpalmberg** [comment]
Recent sample files from December 08, 2022:

- https://www.cnrfc.noaa.gov/archive/2022/Dec/netcdfFcstTemp/fcstTemperature.20221208_0000.nc.gz
- https://www.cnrfc.noaa.gov/archive/2022/Dec/netcdfFcstTemp/fcstTemperature.20221208_0700.nc.gz
- https://www.cnrfc.noaa.gov/archive/2022/Dec/netcdfFcstTemp/fcstTemperature.20221208_1200.nc.gz
- https://www.cnrfc.noaa.gov/archive/2022/Dec/netcdfFcstTemp/fcstTemperature.20221208_1900.nc.gz

Note: File posting time typically looks to be about 1hr 5min after the timestamp on the file.  i.e. 0700 file posted at 0805. Information gleaned from https://www.cnrfc.noaa.gov/arc_search.php?product=netcdfFcstTemp

**Comment by adamscarberry** [comment]
QTF is in inches, migration needs fixed by @adamscarberry

**Comment by adamscarberry** [comment]
NBM QTF is in F, migration needs fixed by @adamscarberry

**Comment by adamscarberry** [comment]
This product was removed from the Cumulus catalog and data acquisition was discontinued until the project issue is resolved.
