### ISSUE TITLE
[PRODUCT]: ABRFC QPE

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#253]
## Product Source (URL Preferred)

Note: The parent directory of this file is named `xmrg_qpe`, but happened to see there are `.nc` files within the directory. Confirmed that these files can be handled with gdal, e.g. `gdalinfo NETCDF:"abrfc_qpe_01hr_2022072913Z.nc":Total_precipitation` for Dataset 1.

> Please confirm that Dataset 1 is the appropriate dataset when implementing.

Example URL: https://tgftp.nws.noaa.gov/data/rfc/abrfc/xmrg_qpe/abrfc_qpe_01hr_2022072913Z.nc

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [x] NetCDF
- [ ] Other (Please provide description below)

**Comment by brettpalmberg** [comment]
Work in progress; SQL for acquirable, suite, product added here: https://github.com/USACE/cumulus-api/pull/335.  Still needs:
- [ ] Geoprocessing
- [ ] Airflow
- [ ] Verification of results `develop`
- [ ] Verification of results `stable`

**Comment by adamscarberry** [comment]
@brettpalmberg airflow PR ready: https://github.com/USACE/airflow-config/pull/158

**Comment by adamscarberry** [comment]
@jeffsuperglide Can you handle the processor for this one?
