### ISSUE TITLE
[PRODUCT]: National QPE Mosaic 1-Hour

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#255]
## Product Source (URL Preferred)

https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/

## Product Description

Information from others:

> A national QPE mosaic is published in grib2. This is the exact same data that merges together all RFC's QPE for the CONUS. That rolling 14-day archive of data is already live and ready to go here: https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/

Helpful Link: https://water.weather.gov/precip/about.php

I _think_ this information is referencing the same underlying data product, hosted on UCAR: https://data.eol.ucar.edu/dataset/21.093 .  Includes archive and information on data changes over the years.

This is the best reference I have seen yet related to RFC products, processing stages, details: https://journals.ametsoc.org/view/journals/wefo/31/2/waf-d-14-00112_1.xml

## Product Format

- [ ] Geotiff
- [x] Grib2
- [ ] NetCDF
- [ ] Other (Please provide description below)

**Comment by brettpalmberg** [comment]
Will require:

- [ ] Airflow Data Acquisition
- [ ] Geoprocessor
- [ ] Testing/Validation of Results (DSS)

**Comment by brettpalmberg** [comment]
> - [ ] Coordinating SQL: USACE/cumulus-api#331

@adamscarberry, thinking we can coordinate the new acquirable, product, suite information - then work from this branch on the airflow (@adamscarberry) geoprocess (@brettpalmberg). Have a good weekend and will plan to connect early next week!

**Comment by adamscarberry** [comment]
Airflow done.  PR ready: https://github.com/USACE/airflow-config/pull/154

**Comment by brettpalmberg** [comment]
Geoprocessor complete; Merging to `develop`.

Merge to stable pending verification of DSS download request.

- [ ] DSS Download results look ok
- [ ] Merge `develop` --> `stable`

**Comment by brettpalmberg** [comment]
Noticing that files may be updated up to a few days past the date of the data. We may need to think about how we ingest this data, if any versioning, hashing (or similar) is needed. Here is an example where precipitation estimates from August 05th are updated on August 8th or after.  This would suggest that several days of hourly precipitation may need to be processed every hour.  Will need to determine if it's ok to overwrite previous grids (keeping "best available") for a given timestamp, or if we need to keep history.

Confirmed that the gdalinfo metadata is identical for files, even if they have been updated at a later date and the file hashes are different. Because the grid values themselves have likely changed `gdalinfo -stats <filename>` does return different results in the STATISTICS_xxx fields (example shown below):
![image](https://user-images.githubusercontent.com/29417036/183533918-ac6780cd-f52f-4f5a-b803-767251dd7913.png)

cc @adamscarberry

**Comment by adamscarberry** [comment]
Sample result: 
![image](https://user-images.githubusercontent.com/46494851/183708322-b5b42c22-9165-49fc-a228-6b224ba913cf.png)

**Comment by adamscarberry** [comment]
DAG enabled in develop.
