### ISSUE TITLE
[FEATURE REQUEST]: Potential Speed-Up for async_packager

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#257]
## Feature Request Type
- [x] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.

A recent DSS download for watershed `NWDM:FPG_LwrYel` took 6-7 minutes to complete with a total output file size of 119MB. This feels a bit on the slow side, there may be some opportunities to speed this up. Specifics for download in question are below.

```
Grid Payload (14-day lookback/15-day forecast)
Watershed:  NWDM:FPG_LwrYel
MBRFC KRF QPE (1-hour)
MBRFC KRF QPF (6-hour) - 7 day fcx
MBRFC KRF Fct Airtemp (1-hour) - 15 day fcx
NDGD RTMA Airtemp (1-hour)
Snodas Cold Content
Snodas Interpolated Cold Content
Snodas SWE
Snodas Interpolated SWE
Download Time:  about 7 minutes
Total DSS file size:  119 MB
```

At minimum, we should gather benchmark information for `async_packager` by product for at least 1 watershed (area of interest) by which to judge any changes for improvement/regressions.

## Describe the solution you'd like

* Gather test data (one file per product)
* Create test case for each product to test this section of the `async_packager` code (https://github.com/USACE/cumulus-api/blob/develop/async_packager/src/cumulus_packager/writers/dss7.py):
```
  warp_ds = gdal.Warp(
      mem_raster,
      ds,
      format="GTiff",
      outputBounds=_bbox,
      xRes=cellsize,
      yRes=cellsize,
      targetAlignedPixels=True,
      dstSRS=destination_srs.ExportToWkt(),
      resampleAlg="bilinear",
      copyMetadata=False,
  )
```

Capture the following information:
  * total request processing time
  * resulting file size
  * Number of network round trips required to `minio (s3)` to complete the request. May be a way to get this from a high debug level output for GDAL (See ConfigParameter CPL_DEBUG: https://trac.osgeo.org/gdal/wiki/ConfigOptions)
* Evaluate potential improvements by adjusting GDAL Configuration Parameter `CPL_VSIL_CURL_CHUNK_SIZE`. Setting this higher than the default (and higher than the default max of 2MB) may reduce network trips to the S3 file, which should reduce total network overhead. Copied from the [GDAL Docs Here](https://gdal.org/user/virtual_file_systems.html):
> Partial downloads (requires the HTTP server to support random reading) are done with a 16 KB granularity by default. Starting with GDAL 2.3, the chunk size can be configured with the CPL_VSIL_CURL_CHUNK_SIZE configuration option, with a value in bytes. If the driver detects sequential reading it will progressively increase the chunk size up to 2 MB to improve download performance. Starting with GDAL 2.3, the GDAL_INGESTED_BYTES_AT_OPEN configuration option can be set to impose the number of bytes read in one GET call at file opening (can help performance to read Cloud optimized geotiff with a large header).
* If this does not provide substantial reduction in processing time, continue investigating other alternatives.

## Describe alternatives you've considered
* This alternative
* Increasing `CPL_VSIL_CURL_CHUNK_SIZE` to a reasonable high value in develop or production service prior to more systematic testing and benchmarking
* [The do nothing alternative](https://www.oreilly.com/library/view/return-on-software/0321228758/0321228758_ch09lev1sec4.html)

**Comment by adamscarberry** [comment]
Please note slow down between old rsgis.dev env and new castle cloud.

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/46494851/183653517-437551f1-8748-45e1-b7e2-9adc00c9102c.png">

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/46494851/183653703-f29b9c73-8b24-46d5-8d95-e0bd7c0c42ee.png">

**Comment by adamscarberry** [comment]
Local test:

- `MRMS-V12 QPE Pass 1 PRECIP 1hr` for 24 hours (24 records) takes 8 sec
- based on the above, 7 days should take around 56 sec (locally)
  - still slower than old rsgis.dev env

**Comment by brettpalmberg** [comment]
Digging into this now.

**Comment by adamscarberry** [comment]
Anything of interest with the newest gdal? https://github.com/OSGeo/gdal/blob/v3.5.1/NEWS.md

**Comment by brettpalmberg** [comment]
> 

Nothing that sticks out that would solve the issue, though I think upgrading & testing w/ new version would be good when convenient.

**Comment by brettpalmberg** [comment]
Trying to narrow down where in the code we should focus our efforts.

Limited testing locally w/ this parameter `CPL_VSIL_CURL_CHUNK_SIZE` for watershed `NWDM:FPG_LwrYel` and ~2 days of MRMS Pass 1 data did not show any significant difference in traffic patterns using wireshark connected to container `cumulus-api-packager-1` container in docker. May need to try larger downloads, different products, different watershed extents to see a difference.

First, going to revive this issue to try writing an output file as a directory of .tif files (maybe zipped) to compare with outputting to DSS7 format: https://github.com/USACE/cumulus/issues/176.

This should tell us if there is significant processing time happening in the way we're writing to DSSv7.

**Comment by brettpalmberg** [comment]
## Results from testing data `async_packager` with output format `dss7` vs. `tgz-cog`

### Test Description

Two output format writers have been implemented for Cumulus. tgz-cog was implemented to help provide comparison for what were perceived as slower-than-expected download times.

    1. `tgz-cog`: a .tar.gz containing TIF files, one per grid timestep
    2. DSS Version 7, a quick test was run to compare output file write times.

17 Hours of MRMS Precipitation (Pass 1) were packaged in both formats for:

    1. a relatively small watershed (NWDM:FPG_LwrYel)
    2. A large watershed (NWDM:MissouriRiver)

Results from Missouri River are shown below.

This is preliminary smoke-test level results, we definitely need to try this comparison against significantly longer time window of grids and different types of grids (Air Temperature has not been evaluated yet) to see if this pattern described in the summary below holds, reverses, or washes out.

### Summary

The `tgz-cog` writer is packaging significantly faster (200-500%) than `dss7` on a relatively small download, but dss7 is providing better compression (smaller output file) when compared apples-to-apples by `gzip`ing the .dss file after download.

The tgz-cog running faster is surprising because the tar.gz requires saving intermediate files to disk, whereas the `dss7` writer reads into memory and writes to dss without requiring the intermediate file written to disk.

We will need to dig deeper into `async_packager`'s dss7 writer implementation to see if there is room for improvement, or if this is to be expected. First item that comes to mind to check is whether we call ".open()" and ".close()" on the .dss file before/after each grid record (as opposed to calling "open()", write all records, then "close()").

### Data

* DSSv7.    : 383K Aug 10 16:55 download_1fd29ac4-3a3c-4190-a5f0-984a66a2beef.dss
* DSSv7 gzip: 207K Aug 10 16:57 download_1fd29ac4-3a3c-4190-a5f0-984a66a2beef_dss_gzipped.gz

**Comment by adamscarberry** [comment]
This function is called at ANY logger level set by env: `dss7.py:25(log_dataset)`.  Recommend not calling in production.

**Comment by brettpalmberg** [comment]
Here are a few updates to the cumulus-api and cumulus-ui that should allow us to test downloads in tgz-cog format in `develop` for rough benchmark. These features need more refinement later (such as fetching download formats as a domain from the API rather than hard-coded array in user interface), but they should not break anything and allows us to test the issue at hand: 

* cumulus-api: https://github.com/USACE/cumulus-api/pull/343 (supports tgz-cog writer option)
* cumulus-ui: https://github.com/USACE/cumulus-ui/pull/142 (adds "Format" dropdown to the download modal, defaults to dss7)

**Comment by adamscarberry** [comment]
This is being printed by the tiffdss.c file when param != 'precip': https://github.com/USACE/cumulus-api/blob/ca44c1b3017e68de9fdbfadcdb56b7c2ece642b8/async_packager/tiffdss/src/tiffdss.c#L39

<img width="512" alt="image" src="https://user-images.githubusercontent.com/46494851/184165023-5cfeda6e-e541-41a1-9585-5f6f4f2f6fa1.png">

**Comment by brettpalmberg** [comment]
> This is being printed by the tiffdss.c file when param != 'precip': https://github.com/USACE/cumulus-api/blob/ca44c1b3017e68de9fdbfadcdb56b7c2ece642b8/async_packager/tiffdss/src/tiffdss.c#L39

Good catch. @jeffsuperglide, can you help w/ PR to remove this `print()` call?

**Comment by adamscarberry** [comment]
Develop (new changes) vs Stable results

| Product      | Watershed | Record Count | Develop | Stable |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| mrms qpe pass1 | LRH-Guyandotte | 145 | 33 sec | 2 min |

**Comment by adamscarberry** [comment]
It appears that a bug with HRRR data was fixed.  The first two hours of this stable dss download was a green display:
https://cumulus-api.corps.cloud/cumulus/download/dss7/download_6cf3a374-e6dc-4203-8eed-90fba3b8772e.dss


![image](https://user-images.githubusercontent.com/46494851/184212685-b58b7a5b-b061-4a9b-b8d1-aa2e29e917e6.png)

**Comment by adamscarberry** [comment]
Note: There was a period of time in July 2022 in develop where SNODAS SWE Interpolated was missing records.  Re-running airflow tasks for those days resolved the issue, so the latest develop code appears good.

**Comment by adamscarberry** [comment]
Multiple Interpolated SNODAS products were missing in stable after 1-Aug-22.  Unsure why.  Re-ran airflow tasks.
