### ISSUE TITLE
[FEATURE REQUEST]: Communicate Product Ingest Status Summary

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#258]
## Feature Request Type
- [x] ***User Interface (UI)***
- [x] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.
Yes.  It's difficult to tell at a glance if data acquisition and processing is behind, perhaps due to system outage or operational issue.  This is amplified as more products, both forecast and observed, are being added to the system. In many cases, it's expected and normal that the latest file for a given product is 1 month old or more. In other cases, the latest file should never be more than 1 hour from the present time.

## Describe the solution you'd like
* Consider adding a column to the product table, indicating a "acceptable timedelta", above which, warning/alert condition would be active to show that the product acquisition/processing is behind what is expected.
* Add a simple minimalist view and corresponding API Endpoint (`/product_ingest_status`?) that shows for each product:
  * product slug 
  * latest_product_datetime
    * For observed products, the datetime should be based on the date of the data.
    * For forecast products, the datetime should be based on the version date (i.e. forecast time).
  * a boolean representing is_current, based on comparing product's acceptable timedelta with **(latest_product_datetime - current_datetime)**.
 
## Describe alternatives you've considered
* Modify Product struct to include optional field(s) describing ingest status. This would update existing endpoints `/products`, `/products/:id` to include a field (e.g. "ingest_is_current" or similar) to the products returned.
* Exporting prometheus-style metrics in-lieu of a more traditional JSON response, scraping with Prometheus, displaying in Grafana.
* Defining alert conditions in a separate service, similar to Grafana/Prometheus alerting capability
* More full-featured alerting capability

## Additional context
There is a lot of room to extend this concept in the future. The intent in the immediate term is to provide a **very** simple, quickly implementable, stopgap solution, live with the solution for a couple months, realize value from it, learn from it, focusing attention on other issues.

**Comment by adamscarberry** [comment]
@brettpalmberg  We could easily do a manual timedelta column value based on timing characteristics of each product. 

Just spitballing...Any thought on using:

If (Now - temporal_duration) >= latest_product_datetime
Then is_current = True

**Comment by brettpalmberg** [comment]
Hey @adamscarberry , thanks for jumping-in. I had a feeling you'd like this task and was hoping you'd be ok taking point as the main assignee.

I don't know that we can rely directly on the temporal_duration or temporal_resolution fields for the status.  I say this thinking about a dataset like Prism, where it's a 1-day (24h) temporal resolution product. However, there may be a 1 month (using rough numbers) lag in when "today's" information is available for ingest. Therefore, the is_current for Prism product should only be `false` when **now - latest_datetime > 1 month**.

On the other end of the spectrum, MRMS Precipitation should return `"is_current": false"` when **now - latest_datetime > 1 hour**

**Comment by adamscarberry** [comment]
Good point. I figured there was a gotcha. 

Wondering if we should factor the "Realtime" tag to determine if a status is displayed. Using a tag for this kinds feels a little unstable, but may work.

**Comment by brettpalmberg** [comment]
Leaving the field that stores "acceptable timedelta" (probably a field with type [8.5.4 Interval Input](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) `NULL` would be a good option to signify that is_current shouldn't be (and can't be) calculated for a given product.

**Comment by adamscarberry** [comment]
@brettpalmberg For your review: https://github.com/USACE/cumulus-api/pull/332

**Comment by brettpalmberg** [comment]
Awesome! Thanks @adamscarberry, I'll take a look now.

**Comment by brettpalmberg** [comment]
Rebased feature branch against latest changes in develop (https://github.com/USACE/cumulus-api/pull/333).  Looks good, merging now.

**Comment by adamscarberry** [comment]
@brettpalmberg   Did you anything changed?

<img width="413" alt="image" src="https://user-images.githubusercontent.com/46494851/183744500-141f9d9a-7686-4099-a444-9551b157c4be.png">

**Comment by brettpalmberg** [comment]
@adamscarberry, looks good to me!  Let's go with it.

**Comment by brettpalmberg** [comment]
Reviewing results in `stable`. One item looks out of place, any idea why we're getting a duplicate here for slug wpc-qpf-2p5km (items 55, 56). I bet we have a few productfile records with bad (or null) version.

![image](https://user-images.githubusercontent.com/29417036/184252653-f861d364-5166-451f-9dbf-09f326934bd4.png)

**Comment by adamscarberry** [comment]
Yep, found the straggler (referenced as item 55 above)

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/46494851/184254529-8c4c39d1-b420-4585-8095-708385829cce.png">

It's fixed. ✅

**Comment by brettpalmberg** [comment]
Confirmed! Nice work. Closing this now. A few notes for later:

* Will circle back in separate GH issues to figure out how we use this in the user interface.
* Query is pretty DB Intensive, which is understandable.  Response from API shows ~3.2 seconds of wait time. Few alternatives that come to mind:
  * Materialized View
  * Actual field on `product` table to hold `latest_datetime`. This gets updated via trigger whenever new productfiles are saved to the database.

**Comment by adamscarberry** [comment]
Agree.  It's slow.
