### ISSUE TITLE
[FEATURE REQUEST]: tiffdss Source Code Move

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#261]
## Feature Request Type
- [x] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.
Feature request is NOT related to a problem.

## Describe the solution you'd like
Source code for `tiffdss` has been moved to its own GitHub repo [***here***](https://github.com/HydrologicEngineeringCenter/tiffdss).  Proposing `Cumulus-api: Packager` remove `tiffdss` source code and have the packager dockerfile clone the new repo to build `libtiffdss.so` from source.

**Comment by brettpalmberg** [comment]
Hey, this looks great @jeffsuperglide! Onward - go for it!

**Comment by brettpalmberg** [comment]
When convenient, @jeffsuperglide, how's this going?  Any details on path forward that can be shared here?

**Comment by jeffsuperglide** [comment]
HTTPS://GitHub.com/HydrologicEngineeringCenter/tiffdss repo setup.  Packager dockerfile just needs updating to clone, build and place shared object in /usr/lib.

**Comment by brettpalmberg** [comment]
Awesome @jeffsuperglide. Let's connect on this tomorrow.

**Comment by jeffsuperglide** [comment]
> [HTTPS://GitHub.com/HydrologicEngineeringCenter/tiffdss](HTTPS://GitHub.com/HydrologicEngineeringCenter/tiffdss) repo setup. Packager dockerfile just needs updating to clone, build and place shared object in /usr/lib.

Above repo updated to accommodate cloning and building in `packager`.  Branch https://github.com/USACE/cumulus-api/tree/feature/tiffdss-src-removal has WIP for `packager` to clone and build from source.

cc @brettpalmberg, @adamscarberry

**Comment by brettpalmberg** [comment]
Awesome, thanks @jeffsuperglide. Will incorporate the branch cumulus-api referenced above and confirm everything is working.

Moving forward, we will now have source code at https://github.com/HydrologicEngineeringCenter/tiffdss as a dependency. We will also use the repository at https://github.com/HydrologicEngineeringCenter/tiffdss to open and track any dss specific issues and enhancement requests.

**Comment by jeffsuperglide** [comment]
@brettpalmberg and @adamscarberry 

Removing the submodule `hec-dss` is related to this issue.  The submodule is not needed after `tiffdss` source code moved out.

**Comment by brettpalmberg** [comment]
Confirmed. Removed .gitmodules and hec-dss in this commit: https://github.com/USACE/cumulus-api/commit/528a0407015461f1c5a99f031c5c0d715fa2fb6d.

**Comment by jeffsuperglide** [comment]
@brettpalmberg can this be closed?

**Comment by brettpalmberg** [comment]
Hey @jeffsuperglide, is there any information we want to document for the future that's not already captured so we can search/find it later? If so, recommend we take the opportunity to document it here (and then close).  If not, please feel free to close this issue.

**Comment by jeffsuperglide** [comment]
@brettpalmberg 

@ktarbet and I discussed possibly making a shared object and executable artifacts available.  This could eliminate the need for cloning the repo and building.  Also, considering versioned packages.

May need to get versioning and publishing packages in GitHub help from @adamscarberry
