### ISSUE TITLE
[PRODUCT]:National QPE Mosaic 6-Hour

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#262]
## Product Source (URL Preferred)

See details and links for National QPE Mosaic at USACE/cumulus#255.

Sample file for 6-Hour QPE: https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/pcpanl.20220809/st4_conus.2022080900.06h.grb2

Because the 6-hour files are not the accumulation of the 1-hour files, we should obtain the 6-hour files for comparison purposes. From the article at https://journals.ametsoc.org/view/journals/wefo/31/2/waf-d-14-00112_1.xml, Section "NCEP Stage IV":

> It is also important to note that the 6-hourly analysis files are not the accumulation of the hourly analysis. The RFCs send hourly and 6-hourly analysis separately. The hourly RMPAs that NCEP receives are not manually quality controlled. However, the 6-hourly analysis that is included in the NCEP stage IV are the precipitation maps that are manually quality controlled at the RFC.

**Comment by brettpalmberg** [comment]
Geoprocessors and SQL data added in this PR: https://github.com/USACE/cumulus-api/pull/334. @adamscarberry, can you help on the Airflow data acquisition?

**Comment by adamscarberry** [comment]
PR ready: https://github.com/USACE/airflow-config/pull/157

**Comment by adamscarberry** [comment]
Sample result: 
![image](https://user-images.githubusercontent.com/46494851/183708634-ac9f84cb-7e62-4e76-ab33-62e376179f2f.png)

**Comment by adamscarberry** [comment]
DAG enabled in develop.
