### ISSUE TITLE
[PRODUCT]: National QPE Mosaic 24-Hour

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#263]
See details and links for National QPE Mosaic at https://github.com/USACE/cumulus/issues/255.

Sample file for 24-Hour QPE: https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/pcpanl.20220808/st4_conus.2022080812.24h.grb2

From the article at https://journals.ametsoc.org/view/journals/wefo/31/2/waf-d-14-00112_1.xml, Section "NCEP Stage IV":

> The 24-h stage IV product reprocessed 24 h after the verification time is the most accurate product for postanalysis of precipitation data.

**Comment by brettpalmberg** [comment]
Geoprocessors and SQL data added in this PR: https://github.com/USACE/cumulus-api/pull/334. @adamscarberry, can you help on the Airflow data acquisition?

**Comment by adamscarberry** [comment]
sample result: 
![image](https://user-images.githubusercontent.com/46494851/183708876-f53ed574-f5f9-468a-847f-0c898c488956.png)

**Comment by adamscarberry** [comment]
DAG enabled in develop.
