### ISSUE TITLE
Ensure API Handle Null Productfile Version

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#266]
Documenting for another time as I am reviewing code.  Productfiles that are not "versioned" have a default version date in the database of "1111-11-11 11:11:11" (or similar). I can't remember if the API gracefully handles the case where version on a POST payload is null or not included in the payload.

Saving "unversioned" productfiles with the known version date ("1111-11-11 11:11:11") seems like an implementation detail only the database and api should know about. Suggest we review the API and database to see if this is handled gracefully already. If the API handles this for us, we can remove any checks for null version information like this to simplify the logic: https://github.com/USACE/cumulus-api/blob/e5f435875e035ae6474dcb4db335b313358fd70a/async_geoprocess/worker.py#L127.

**Comment by adamscarberry** [comment]
I am adding a new test called `CreateProductfile` in postman.  Local testing indicates that we have it setup properly.

Assuming `CreateAcquirablefile` is run first, this test will succeed with a version of 1111-11-11:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/46494851/183976681-247c268c-ba6f-4c05-97df-6229e866f47b.png">

database results:

![image](https://user-images.githubusercontent.com/46494851/183976821-2528522d-eafc-4148-b02d-3942d79f93ee.png)

The same result is true if version is set to `null` in the payload.

**Comment by brettpalmberg** [comment]
Awesome! Nice work and love the addition of test coverage. 🙌🏻

**Comment by brettpalmberg** [comment]
With this confirmed, recommend we remove the redundant logic from the `async_geoprocess` worker. By removing this, it puts full responsibility on the `process()` plugin to set versions appropriately, or not set them at all and let the API handle the version by leaving it out of the POST payload. The reason for removing this logic from the async_geoprocess worker is, if we ever change the way we "version" unversioned files (using the 1111-11-11... version date), this only has to be changed in one place (the API). It also removes mental overhead / cognitive load for future developers as they will not have to figure out what `product_versioning()` does.

**Comment by brettpalmberg** [comment]
Working on this here: 266-ensure-api-handle-null-productfile-version
