### ISSUE TITLE
[FEATURE REQUEST]: Add Unittest for Each Geoprocess Plugin

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#267]
## Feature Request Type

Add testing approach using python `unittest` for each geoprocessor in `async_geoprocess`. This will provide the framework for developers to confidently add new data products and detect changes/updates in grid format or metadata for a given product that may cause the original geoprocessor as-developed to stop working.

For all future product additions, having unit tests will be required for merge to `develop` branch. This is an important step for our team and for potentially adding contributors to the project in the future.

**Comment by brettpalmberg** [comment]
@jeffsuperglide, thanks for your foundational work on this. I'll help carry this the last yard 🏈 and close this one out.

Please commit and push existing work here:
  * unit tests: https://github.com/USACE/cumulus-geoproc
  * test data: https://github.com/USACE/cumulus-geoproc-test-data

**Comment by jeffsuperglide** [comment]
Test data added: https://github.com/USACE/cumulus-geoproc-test-data

cc @brettpalmberg, @adamscarberry

**Comment by jeffsuperglide** [comment]
Unit test for geo-processors added to https://github.com/USACE/cumulus-geoproc/feature/unit-tests

cc @brettpalmberg, @adamscarberry

**Comment by brettpalmberg** [comment]
Awesome, thanks @jeffsuperglide. I'll take a look and start to incorporate into the build. This will really help.

**Comment by brettpalmberg** [comment]
Working concept with cursory usage documentation in README.md at [`develop` branch here](https://github.com/USACE/cumulus-geoproc). Additional refinements, test cases, sample files are still needed but sharing a "hello world" version now. Feedback on the approach is most welcome.

**Comment by jeffsuperglide** [comment]
Dockerfile doesn't need to `pip install` those packages if the package itself is installed.  Copy over the top level directory (cumulus-geoproc) and install.

```
COPY . .
RUN python -m pip install /cumulus-geoproc/
```
setup.cfg defines the package directory

```
[options]
package_dir =
    = src
```

**Comment by adamscarberry** [comment]
`COPY cumulus-geoproc-test-data/fixtures/ /src/tests/integration/fixtures/`

There is no fixtures dir after first clone.

**Comment by brettpalmberg** [comment]
Vast majority of geoprocess processors have been added to default test suite or a custom test suite.

## Integration Test Coverage

- [ ] abrfc-qpe-01h.py
- [ ] cbrfc-mpe.py
- [ ] cnrfc-qpe-06h.py
- [ ] hrrr-total-precip.py
- [ ] lmrfc-qpe-01h.py
- [ ] lmrfc-qpf-06h.py
- [ ] marfc-fmat-06h.py
- [ ] marfc-nbmt-01h.py
- [ ] marfc-nbmt-03h.py
- [ ] marfc-rtmat-01h.py
- [ ] mbrfc-krf-fct-airtemp-01h.py
- [ ] mbrfc-krf-qpe-01h.py
- [ ] mbrfc-krf-qpf-06h.py
- [ ] naefs-mean-06h.py
- [ ] nbm-co-01h.py
- [ ] ncep-mrms-gaugecorr-qpe-01h.py
- [ ] ncep-mrms-v12-msqpe01h-p1-alaska.py
- [ ] ncep-mrms-v12-msqpe01h-p1-carib.py
- [ ] ncep-mrms-v12-msqpe01h-p2-alaska.py
- [ ] ncep-mrms-v12-msqpe01h-p2-carib.py
- [ ] ncep-mrms-v12-multisensor-qpe-01h-pass1.py
- [ ] ncep-mrms-v12-multisensor-qpe-01h-pass2.py
- [ ] ncep-rtma-ru-anl-airtemp.py
- [ ] ncep-stage4-mosaic-01h.py
- [ ] ncep-stage4-mosaic-06h.py
- [ ] ncep-stage4-mosaic-24h.py
- [ ] ncrfc-fmat-01h.py
- [ ] ncrfc-mpe-01h.py
- [ ] ncrfc-rtmat-01h.py
- [ ] ndfd-conus-airtemp.py
- [ ] ndfd-conus-qpf-06h.py
- [ ] ndgd-leia98-precip.py
- [ ] ndgd-ltia98-airtemp.py
- [ ] nohrsc-snodas-assimilated.py
- [ ] nohrsc-snodas-unmasked.py
- [ ] nsidc-ua-swe-sd-v1.py
- [ ] prism-ppt-early.py
- [ ] prism-ppt-stable.py
- [ ] prism-tmax-early.py
- [ ] prism-tmax-stable.py
- [ ] prism-tmin-early.py
- [ ] prism-tmin-stable.py
- [ ] serfc-qpe-01h.py
- [ ] serfc-qpf-06h.py
- [ ] wpc-qpf-2p5km.py
- [ ] wrf-columbia-airtemp.py
- [ ] wrf-columbia-precip.py
