### ISSUE TITLE
[PRODUCT]: Add NWRFC Products to Cumulus

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#268]
## Product Source (Sample Pattern)
- [ ] #278
- [ ] #279
- [ ] #280
- [ ] #281

## NWD POCs
Eric C., Sonja M., Kevin M., and Ross W.

## Product Format
- [x] NetCDF

**Comment by brettpalmberg** [comment]
Hey @FHanbali, excellent! I think this will be a great set of products to add. To my knowledge - these are not included in the NCEP Stage IV CONUS Mosaic.

Would love to plan this as a project we can work closely with the NWD team so they're involved in every step of the process. Recommend we have a kickoff meeting with them to discuss the products, exchange relevant information. Let's connect this week on schedule date for this work.

**Comment by brettpalmberg** [comment]
Breaking this into 4 separate issues, one for each of the 4 data products.

- [ ] NWRFC Temperature Forecast 
- [ ] NWRFC Temperature "Observed"
- [ ] NWRFC Precipitation Forecast
- [ ] NWRFC Precipitation "Observed"
