### ISSUE TITLE
[BUG REPORT]: Tag Order Inconsistent Across Products

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#269]
## Describe the bug

When applying tags to products, it's possible to apply the same 2 tags in the different order. Upon refresh/refetch, the tag order does not adjust for consistent order across products.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/29417036/184251053-74b8748c-296a-4634-b254-7a607563b054.png">

We should probably sort tags alphabetically or via another consistent sorting across all products at the API on the way out.

**Comment by adamscarberry** [comment]
This one is a challenge as you can't sort UUIDs in postgresql.  Still looking...

**Comment by brettpalmberg** [comment]
Any way to sort on the slug first so the UUIDs magically show up in alphabetical order (by tag slug)? https://github.com/USACE/cumulus-api/blob/stable/sql/common/R__04_views_products.sql#L17-L22

What would be really nice would be to have product tags be an array of the slugs rather than UUIDs, but this would require some SQL changes in other places (and some minor UI changes)
