### ISSUE TITLE
NWRFC Forecast Temperature

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#278]
"Forcings" (precip/airtemp) grids from NWRFC

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29417036/207171827-1cbcead3-5414-4e03-9786-0104cf384faf.png">

Updated sample file: https://www.nwrfc.noaa.gov/weather/netcdf/2022/20221212/QTF.2022121212.nc.gz .

> Note: It looks like only current day is posted, so the link above may not be very durable for retrieving a sample file after today. Will have to fiddle the date numbers in the URL.

**Comment by adamscarberry** [comment]
QTF is in F, migration needs fixed by @adamscarberry

**Comment by adamscarberry** [comment]
Local testing results:

![image](https://user-images.githubusercontent.com/46494851/207965396-22d41e4f-aabb-4ec7-96aa-a0983df69012.png)

**Comment by brettpalmberg** [comment]
Data acquisition and processing enabled in develop & stable; complete; closing issue
