### ISSUE TITLE
NWRFC "Observed" Temperature

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#279]
"Forcings" (precip/airtemp) grids from NWRFC

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29417036/207171827-1cbcead3-5414-4e03-9786-0104cf384faf.png">

Updated sample file: https://www.nwrfc.noaa.gov/weather/netcdf/2022/20221212/QTE.2022121212.nc.gz .

> Note: It looks like only current day is posted, so the link above may not be very durable for retrieving a sample file after today. Will have to fiddle the date numbers in the URL.

**Comment by brettpalmberg** [comment]
Contains 6-hour interval grids, 4 total.  Covering the past 24 hour period. Will add sample file to USACE/cumulus-geoproc-test-data shortly.

**Comment by adamscarberry** [comment]
QTE is in inches, migration needs fixed by @adamscarberry

**Comment by adamscarberry** [comment]
Local resulting DSS:

![image](https://user-images.githubusercontent.com/46494851/207962977-8b5b7d55-fe40-4813-86df-995de888f243.png)

**Comment by brettpalmberg** [comment]
Data acquisition and processing enabled in develop & stable; complete; closing issue
