### ISSUE TITLE
NWRFC Forecast Precip

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#280]
Sample File: ~https://www.nwrfc.noaa.gov/weather/netcdf/2022/20220810/QPF.2022081012.nc.gz~

**Comment by brettpalmberg** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29417036/207171827-1cbcead3-5414-4e03-9786-0104cf384faf.png">

Updated sample file: https://www.nwrfc.noaa.gov/weather/netcdf/2022/20221212/QPF.2022121212.nc.gz .

> Note: It looks like only current day is posted, so the link above may not be very durable for retrieving a sample file after today.

**Comment by brettpalmberg** [comment]
Sample file contains 6-hour interval grids, covering approximately 10 days into the future. Will add sample file to USACE/cumulus-geoproc-test-data shortly.

**Comment by adamscarberry** [comment]
QPF is in inches, migration needs fixed by @adamscarberry

**Comment by brettpalmberg** [comment]
geoprocessor implemented, thanks @jeffsuperglide 👍🏻 Merged: https://github.com/USACE/cumulus-geoproc/pull/29.

**Comment by adamscarberry** [comment]
DSS result of testing:

![image](https://user-images.githubusercontent.com/46494851/207960527-7f8e6f61-59e3-4968-818d-fd0a5ffc99be.png)

**Comment by brettpalmberg** [comment]
Data acquisition and processing enabled in develop & stable; complete; closing issue
