### ISSUE TITLE
NWRFC "Observed" Precip

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#281]
Sample File: ~https://www.nwrfc.noaa.gov/weather/netcdf/2022/20220810/QPE.2022081~

**Comment by adamscarberry** [comment]
This share is a bit challenging to figure out.  

As of 12/12/22, here is a sample QPE that works: 
https://www.nwrfc.noaa.gov/weather/netcdf/2022/20221212/QPE.2022121212.nc.gz

**Comment by brettpalmberg** [comment]
@adamscarberry, this looks good. Just found this and will update the other NWRFC product issues also. Let's start by just getting the 12z file (`-----12.nc.gz`) - this may be the only file naming convention that is posted.

**Comment by brettpalmberg** [comment]
The QPE file contains 6hr grids (4 of them) - suspect this covers the past 24 hours of precipitation.

**Comment by adamscarberry** [comment]
QPE is in inches, migration needs fixed by @adamscarberry

**Comment by brettpalmberg** [comment]
geoprocessor implemented, thanks @jeffsuperglide 👍🏻 Merged: https://github.com/USACE/cumulus-geoproc/pull/28.

**Comment by brettpalmberg** [comment]
Data acquisition and processing enabled in develop & stable; complete; closing issue
