### ISSUE TITLE
Geoprocess Image `osgeo/gdal:ubuntu-small-*` Does Not Support NetCDF

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#283]
I just noticed that the `osgeo/gdal:ubuntu-small-3.5.0` Docker Image we are using currently does not contain NetCDF support by default. NetCDF (.nc) support for GDAL makes it a breeze to work with .nc files, as you can use the syntax NETCDF:<filename>:<subdataset name> to access a gdal.Dataset object.  I believe this could simplify some of the geoprocess code, but @jeffsuperglide should definitely weigh in.

```>>> from osgeo import gdal
>>> ds = gdal.Open('NETCDF:QPE.2022081012.nc:QPE')
>>> ds.RasterCount
4
```

To get NetCDF support, we would need to switch to a osgeo/gdal:ubuntu-full-* image, which is large (~1G). Perhaps we could use an alpine based image such as osgeo/gdal:alpine-normal-3.5.1 (88mb).

**Comment by adamscarberry** [comment]
comparison: https://github.com/OSGeo/gdal/tree/master/docker

**Comment by jeffsuperglide** [comment]
Having GDAL with netCDF driver is nice but does not mean it works on all netCDF files.  Recently added products from `ABRFC` and ` NCRFC` are netCDF-3, which did not work well with GDAL.  PROJ was used to process these products in Polar Stereographic.  Need to make sure that is available.  Also, the current image being used has `libgdal.so` shared object that is used to compile `tiffdss`.

**Comment by jeffsuperglide** [comment]
> I just noticed that the `osgeo/gdal:ubuntu-small-3.5.0` Docker Image we are using currently does not contain NetCDF support by default. NetCDF (.nc) support for GDAL makes it a breeze to work with .nc files, as you can use the syntax NETCDF:: to access a gdal.Dataset object. I believe this could simplify some of the geoprocess code, but @jeffsuperglide should definitely weigh in.
> 
> ```
> >>> ds = gdal.Open('NETCDF:QPE.2022081012.nc:QPE')
> >>> ds.RasterCount
> 4
> ```
> 
> To get NetCDF support, we would need to switch to a osgeo/gdal:ubuntu-full-* image, which is large (~1G). Perhaps we could use an alpine based image such as osgeo/gdal:alpine-normal-3.5.1 (88mb).

cc @adamscarberry 

@brettpalmberg - is correct in his assessment between the two images.  I've been testing Weather Research and Forecasting (WRF) for Columbia River Basin and it's best to use `osgeo/gdal:ubuntu-full-` to utilize GDAL and `netCDF` driver.  Not having `tiffdss` in the `cumulus-geoproc` repo may not require `ubuntu` now that it is compiled in its own repo.  Future thought is to have a `tiffdss` archives already compiled.

**Comment by brettpalmberg** [comment]
@jeffsuperglide, if the `osgeo/gdal:ubuntu-full-` image is needed to support the wrf files project, definitely open to a PR in the cumulus-geoproc repository.

**Comment by adamscarberry** [comment]
switched in full image in commit: https://github.com/USACE/cumulus-api/commit/e4083de48d8eeda6d0737af4739b55d1bdb4cfef
