### ISSUE TITLE
[FEATURE REQUEST]: National QPE STAGE4 Mosaic - retrieve prior hours

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#285]
## Feature Request Type
- [ ] ***User Interface (UI)***
- [x] ***Application Programming Interface (API)***

Follow up to:

- https://github.com/USACE/cumulus/issues/255
- https://github.com/USACE/cumulus/issues/262
- https://github.com/USACE/cumulus/issues/263

## Issue ##
Based on watching the source data folder and timestamps it appears prior hours are updated after they are originally published.

## Describe the solution you'd like
Modify newly created airflow dags for the above products to look-back and re-acquire previous n files.

Add prior hours retrieval to:

- [x] 01h DAG
- [x] 06h DAG
- [ ] 24h DAG - does not apply to 24hr product

**Comment by adamscarberry** [comment]
@brettpalmberg Currently working on the 01h DAG.  Thinking we do the following:

- Download/notify for last 6 products every other hour.

**Comment by brettpalmberg** [comment]
Hey @adamscarberry, thanks for digging into this. It looks like if we take a look at Last Modified timestamps of "Today" (Tuesday, Aug 16th), we're seeing modifications to files with datetimes as old as 5 days ago. That to say, I think we need to download and notify much further back than the previous 6 files. Rough numbers, looks like the past ~150 files (6 days * 24 hours). Looking at https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/pcpanl.20220811/.

![image](https://user-images.githubusercontent.com/29417036/184895299-ae1d27b5-7854-45ac-8005-3e03e37c7f4a.png)

@FHanbali, it would be helpful if we could connect w/ NCEP to understand if there is a set amount of time they will update Stage IV Mosaic files back from present.  It looks like ~5days, but hard to tell _exactly_ from the timestamps without some guessing.

**Comment by adamscarberry** [comment]
Thanks for the review.  That's awful, but we'll deal with it.  With that kind of lookback, how frequent should we grab all those files?  Every other hour seems excessive now.

**Comment by brettpalmberg** [comment]
I know it seems like a lot, but I'm thinking every hour we download and reprocess the latest available files for at least the past 5 days 🔥

**Comment by adamscarberry** [comment]
I will have to put a sleep between download requests to avoid this:
`
urllib.error.HTTPError: HTTP Error 302: Your allowed limit has been reached. Please go to https://www.weather.gov/abusive-user-block for more info`

**Comment by adamscarberry** [comment]
Adding the lookback functionality to the 01h dag (with a 2 sec sleep to prevent rate limiting), the total task instance time went from 8 sec to just over 5 min.

**Comment by brettpalmberg** [comment]
That makes sense! 2 seconds sleep * 5 days * 24 hr/day = 4min of sleep time if running sequentially w/ concurrency 1.
