### ISSUE TITLE
Decouple Cumulus Geoprocessing Library from `cumulus-api/async_geoprocess`

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#289]
The cumulus_geoproc library, currently stored at https://github.com/USACE/cumulus-api/tree/stable/async_geoprocess/src/cumulus_geoproc, can stand on its own and can be `pip install`ed in the existing USACE/cumulus-api/async_geoprocess container.

There's a lot going on in the cumulus-api repository, with many containers, Dockerfiles, and docker-compose files.  Moving cumulus-geoproc to a dedicated repository will help with testing strategy and provide other benefits.

New Repository for cumulus-geoproc: https://github.com/USACE/cumulus-geoproc

Additional details will be forthcoming in thread below.

cc @jeffsuperglide

**Comment by jeffsuperglide** [comment]
cumulus_geoproc and cumulus_packager Python packages do have some of the same modules between them.

**Comment by brettpalmberg** [comment]
@jeffsuperglide, here is a quick (and I am sure I broke it) move to start.

Most everything from github.com/USACE/cumulus-api/async_geoprocess/* moved here: https://github.com/USACE/cumulus-geoproc .  There will be some pieces that architecturally should move back w/ async_geoprocess/worker.py .

We'll figure it out.

**Comment by brettpalmberg** [comment]
Jotting down some ideas to talk about tomorrow:

* Optimizing the developer experience for fast feedback in cumulus-geoproc when adding new products (minimizing container reboots, mounting source code in container, workflow for running unit tests, etc.)
* Moving contents of [handler.py]() back into USACE/cumulus-api/async_geoprocess/ somewhere, perhaps right in worker.py.
* Moving [configurations.py](https://github.com/USACE/cumulus-geoproc/blob/develop/src/cumulus_geoproc/configurations.py) adjacent to USACE/cumulus-api/async_geoprocess/worker.py
* [cumulus_geoproc.capi](https://github.com/USACE/cumulus-geoproc/blob/develop/src/cumulus_geoproc/utils/capi.py) looks like the start of a generalized cumulus-python-sdk. Let's talk about it.  May be a good candidate for a separate repository used by both [async_geoprocess](https://github.com/USACE/cumulus-api/blob/stable/async_geoprocess/src/cumulus_geoproc/utils/capi.py) and [async_packager](https://github.com/USACE/cumulus-api/blob/stable/async_packager/src/cumulus_packager/utils/capi.py) like you were alluding to.  Another option we could consider if `cumulus-python-sdk` is a thing is writing the client in Go and wrapping it with python. This does afford nice developer experience of directly use github.com/USACE/cumulus-api/models in the client.

**Comment by brettpalmberg** [comment]
> Optimizing the developer experience for fast feedback in cumulus-geoproc when adding new products (minimizing container reboots, mounting source code in container, workflow for running unit tests, etc.)

This has been completed. All product geoprocessing capability has been encapsulated in a single repository here: https://github.com/USACE/cumulus-geoproc

Additional items may need to be refactored from `cumulus-geoproc` back into `cumulus-api/async-geoprocess` at a later date. Currently, everything is working and no more changes intended prior to Oct 01, 2022.
