### ISSUE TITLE
[BUG REPORT]: NCEP-RTMA-RU files storing without date

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#292]
Acquirables/Products have been storing in S3 and DB with only a time (no date) which has resulted in files overwriting (bad records prior to current day).

Remedy:
- [x] Add date to acquirable via airflow change
- [x] purge database productfiles without date
- [x] re-run last few days in airflow to populate recent data

**Comment by brettpalmberg** [comment]
Good catch @adamscarberry

**Comment by adamscarberry** [comment]
example file value in productfile looks like: 
`cumulus/products/ncep-rtma-ru-anl-airtemp/rtma2p5_ru.t1130z.2dvaranl_ndfd.grb2.tif`

Will run the following sql to cleanup:

```
delete from cumulus.productfile 
where product_id = 'e4fdadc7-5532-4910-9ed7-3c3690305d86'
and file not like '%airtemp/20%'
```

**Comment by adamscarberry** [comment]
re-ran a small time window back.  doesn't really matter until we get https://github.com/USACE/cumulus/issues/290 resolved
