### ISSUE TITLE
[BUG REPORT]: NBM QPF - Geoproc - wrong band 

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#297]
Wrong band is being selected for geoproc:

![image](https://user-images.githubusercontent.com/46494851/186244298-c25564b1-ba89-4f86-a857-743141de5989.png)

Should be addressed in : https://github.com/USACE/cumulus/issues/296 - it was not

**Comment by brettpalmberg** [comment]
@adamscarberry, I'll work on test coverage around this one. Stay tuned!

**Comment by adamscarberry** [comment]
thanks @brettpalmberg   looks good

## QPF Verification

![image](https://user-images.githubusercontent.com/46494851/186712437-f5890904-c41d-4778-9c0d-06b62ae44201.png)


## Airtemp verification

![image](https://user-images.githubusercontent.com/46494851/186712078-cdc40c56-dc5a-49d9-8ffd-f9c02d9ebc3d.png)
