### ISSUE TITLE
[BUG REPORT]: NBM acquirables/products missing date in filename

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#298]
This will cause overwrites in S3 and serve incorrect past records.

- [x] Fix airflow dag to include date in filename
- [ ] review data in S3/db to determine what records to purge

---

- Last properly timestamped acquirables in S3 stable (before fix) = 20220216

**Comment by adamscarberry** [comment]
![image](https://user-images.githubusercontent.com/46494851/186252877-3c7ddd0c-a120-4b03-8299-1d51eff1c727.png)

**Comment by adamscarberry** [comment]
Fixed

![image](https://user-images.githubusercontent.com/46494851/186266564-8a5e56a2-bda1-40cd-9740-2ea21bb01a5f.png)


Deployed to:

- [ ] develop
- [ ] stable

**Comment by adamscarberry** [comment]
Before the refactor, it looks like the productfile was being saved in the format of:
`cumulus/products/nbm-co-qpf/blend.t07z.core.f020.co-20220610-nbm-co-qpf.tif`

The processor was adding the datetime to the file (no longer happening).

Those productfiles should be good and will be kept.

The following queries will delete productfiles that look like:
`cumulus/products/nbm-co-qpf/blend.t11z.core.f035.co.tif`
`cumulus/products/nbm-co-airtemp/blend.t18z.core.f009.co.tif`

```
-- delete nbm-co-qpf
delete from cumulus.productfile 
where product_id = '5317d1c4-c6db-40c2-b527-72f7603be8a0'
and file not like '%-20%' and file not like '%/blend.20%';
```
```
-- delete nbm-co-airtemp
select * from cumulus.productfile 
where product_id = 'd0c1d6f4-cf5d-4332-a17e-dd1757c99c94'
and file not like '%-20%' and file not like '%/blend.20%';
```

**Comment by adamscarberry** [comment]
- [ ] Delete develop productfiles
- [ ] Delete develop acquirablefiles
- [ ] Delete develop S3 productfiles
- [ ] Delete develop S3 acquirablefiles
- [ ] Delete stable productfiles
- [ ] Delete stable acquirablefiles
- [ ] Delete stable S3 productfiles
- [ ] Delete stable S3 acquirablefiles

**Comment by brettpalmberg** [comment]
>  Delete develop acquirablefiles (134,476) - query time over 60+ min :-(

Yikes.

**Comment by adamscarberry** [comment]
@brettpalmberg Looking into adding index.

Thoughts on adding this?

`CREATE INDEX IF NOT EXISTS acquirablefile_acquirable_id_idx ON acquirablefile (acquirable_id);`

**Comment by brettpalmberg** [comment]
@adamscarberry, this looks good. Excited to see how this speeds things up.

**Comment by adamscarberry** [comment]
Index added in develop and stable manually.  Will be included in API migrations shortly.

**Comment by adamscarberry** [comment]
Reopening to verify cleanup
