### ISSUE TITLE
[QA Review]: geoproc dst param

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#307]
Does dst need to be defined as a param?  It was removed in the Aug 10th refactor.

![image](https://user-images.githubusercontent.com/46494851/187447877-1543a3b7-7694-4552-b8c6-edd74744d6a3.png)

https://github.com/USACE/cumulus-geoproc/blob/7a29d8824c66b30ae8de4b597129225c9a914ae0/src/cumulus_geoproc/geoprocess/handler.py#L56

**Comment by jeffsuperglide** [comment]
@adamscarberry - The `dst` argument does not need to be assigned.  Processors default to the source's parent directory if the destination is None.
