### ISSUE TITLE
[BUG REPORT]: Cumulus site login is not working

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#310]
## Steps To Reproduce
1. Go to 'https://cumulus.corps.cloud'
2. Click on 'login'
3. Nothing happen and no errors

## Expected behavior
Expected CAC login dialog to pop up

## Actual behavior
Nothing happened.

**Comment by brettpalmberg** [comment]
@FHanbali, thanks for reporting. The auth certificate expired yesterday, it has been updated. Cumulus should be working again as expected. New certificate is valid through December 06, 2022.
