### ISSUE TITLE
[QA Review]: RFC Observed Precip Data Overwrite Window

### ISSUE THREAD

**Issue by msweier** [USACE/cumulus#315]
## Describe what is to be reviewed
Hello @brettpalmberg, MVP had a meeting with the NCRFC a couple weeks ago, and I learned that the "observed" precip grids are continuously refined for sometimes up to a month after the initial distribution. There are no quality codes that designate approval, but generally the bigger the event, the longer it takes to refine it. Maybe you guys are aware of this already.

I'm curious how far back does Cumulus pull from its data sources and is it long enough to incorporate these edits in the rainfall grids?

NCRFC would be happy to meet with you guys regarding this and any other matters (e.g. forecasted temp grids).

**Comment by brettpalmberg** [comment]
Hey @msweier, thanks for this! Wanted to acknowledge this quickly, we will need to circle back to provide the technical details after refreshing our memory on how we're retrieving this particular data product. I think coordinating/meeting with NCRFC in the near future would be great and most appreciated.

**Comment by msweier** [comment]
Sounds good @brettpalmberg. I will working on setting up a meeting with some folks at NCRFC.

**Comment by brettpalmberg** [comment]
cc @FHanbali @adamscarberry @jeffsuperglide

**Comment by adamscarberry** [comment]
This is one a few times where LDM acquisition has the advantage.  We will reprocess whatever is sent no matter the age.

Here are records where the difference between the actual product data time vs when it was received are greater than 3 days:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/46494851/196778155-e76920bb-2069-408d-bf2b-4ab9b033b5f8.png">

Anytime we get the same file/record, the `update_date` column is updated.

**Comment by adamscarberry** [comment]
@brettpalmberg Can we close this issue?

**Comment by brettpalmberg** [comment]
@adamscarberry, I think we're all set. Thanks for the detailed info and screenshot. Closing now.
