### ISSUE TITLE
[PRODUCT]: "rtsutils_init.py" for Cumulus/ CWMS CAVI/HEC_RTS Script not working for me

### ISSUE THREAD

**Issue by ColbyCurtis** [USACE/cumulus#318]
I have followed the steps for importing the most recent cumulus script, however CWMS-CAVI keeps telling me to restart CAVI to apply changes. Yet, once I restart and re-run, it tells me the same message. Everything on my end appears the same as the instructions. Thanks 
![image](https://user-images.githubusercontent.com/119517002/204838940-0c047d4d-f573-43bc-8131-ef4b672c292d.png)

**Comment by brettpalmberg** [comment]
Hey @jeffsuperglide, mind if we assign this one to you?

**Comment by jeffsuperglide** [comment]
@ColbyCurtis - The `initialization` script is only executed once for the watershed you want the scripts in.  Any updates are done with the `rtsutils_update` script.  The `initialization` will overwrite CAVI scripts that come with the distribution (e.g. cumulus.py, cwms_radar.py, get_usgs.py, etc).  If any of these are modified, the name should be changed or those modifications will be lost with an update.

**Comment by ColbyCurtis** [comment]
Gotcha, thanks for clearing that up!

**Comment by brettpalmberg** [comment]
@ColbyCurtis, can you let us know if this addresses the issue you were running into?  If so, we'll go ahead and close this ticket. Thanks!

**Comment by ColbyCurtis** [comment]
Yes. this addresses the issue I was having. Thanks
