### ISSUE TITLE
LDM Outage in Development Environment

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#321]
The Unidata Local Data Manager (LDM) service running in Development environment was stopped or hung last week. This was determined when a user reported the https://github.com/USACE/cumulus product "MBRFC KRF QPE precip 1hr" was missing recent data files.

**Comment by jeffsuperglide** [comment]
LDM on EC2 working this afternoon.  Plan to let it run and check again Tue morning (13DEC).

@brettpalmberg , @adamscarberry

**Comment by jeffsuperglide** [comment]
LDM on EC2 refactored to better handle discovered issues.

- updated permissions allowing uploads to S3 and product notifications to Cumulus
- Dockerfile and docker-compose.yml updated
    - base image unidata/ldm-docker instead of building from source
    - removed many lines of configuration
    - overall cleaner setup
    - seems to have solved quirky user:group and permissions
- new logs shell script with list file controlling log rotation
- updates to Python scripts, appkey and grid_upload_castle
    - logging in scripts using logging.handlers.WatchedFileHandler to sync with log rotation
- new changes merged into `ldm-config` `develop`
