### ISSUE TITLE
[Packager]: Verify Functionality for Polar Stereographic CRS Grids

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#323]
Several new products being incorporated into Cumulus that reference a Polar Stereographic coordinate system. These include at least:

- USACE/cumulus#248
- USACE/cumulus#249

Verify that the Cumulus `async_packager` (component that clips, spatially transforms, and packages grids into a single file for download) can handle the spatial transformation. This can be verified by trying a download for the respective products.

**Comment by adamscarberry** [comment]
Packager errors on QPE, assuming it will also error on QPF:

![image](https://user-images.githubusercontent.com/46494851/207932715-959ade78-6b4f-41c6-8c5b-a2a76fe2d273.png)

**Comment by brettpalmberg** [comment]
I was able to reproduce the same error locally so we can debug and test different arguments w/ `gdalwarp`.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/29417036/207935974-bbfe5a09-962e-4cb7-bbd0-0ddf0772c1e4.png">

Steps to get sample dataset locally:

1. Clone https://github.com/USACE/cumulus-geoproc.
2. Run tests with the "keep" option to keep output Cloud Optimized Geotiff files after processing. This is done with the command `./tests.sh -k` from the root of repository USACE/cumulus-geoproc.
3. Get a shell in the container, with output files mounted for interactive testing. From the root of USACE/cumulus-geoproc, run command: `docker run -v $PWD/cumulus-geoproc-test-data/fixtures:/src/tests/integration/fixtures -v $PWD/cumulus-geoproc-test-results:/output --entrypoint=bash -it cumulus-geoproc-tests:latest`
4. Navigate to directory with sample COG: `cd /output/cnrfc-qpe-06h`
5. Run gdalwarp command: `gdalwarp -t_srs EPSG:5070 ./qpe.20220803_1200.tif test.tif`
6. Evaluate alternatives

Ultimately, I think the sections of the code in `async-packager` that will be modified are:

- https://github.com/USACE/cumulus-api/blob/7d4db1f6f120f89b4e77d3d0e42d7f3eec99dcba/async_packager/src/cumulus_packager/writers/tgz-cog.py#L76-L89
- https://github.com/USACE/cumulus-api/blob/7d4db1f6f120f89b4e77d3d0e42d7f3eec99dcba/async_packager/src/cumulus_packager/writers/dss7.py#L126-L137

**Comment by brettpalmberg** [comment]
Adjustment in strategy, will not make any code changes in cumulus_packager at this time. Plan is to set additional coordinate parameters in the initial `productfile` generation process. M.O. is for all `productfiles` (by the time they are COGs) to have a properly defined geotransform and projection defined so they can be acted upon w/ gdal utilities (gdalwarp, gdal_translate, etc.).

**Comment by brettpalmberg** [comment]
Confirmed that strategy is working to produce `productfiles` (COGs) that have coordinate reference system defined so that cumulus_packager can produce DSS files.

Closing issue now.  cc @adamscarberry, @jeffsuperglide, @FHanbali
