### ISSUE TITLE
[FEATURE REQUEST]: Adjust download modal UI possible date selections

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#331]
Both `Start date` and End date` are allowed to go into the future, this doesn't make sense based on current forecast version practices.

Suggested change

- Prevent `start date` from going into future, stopping at current date/time
- `End date` is already not allowed to be less than start date, also prevent it from going past a couple hours into future.

**Comment by adamscarberry** [comment]
@jeffsuperglide  @FHanbali  Web UI changed to prevent future end date selections

**Comment by FHanbali** [comment]
Thx Adam, it seems the GUI still allows a future selection of a couple of hours into the future causing failed download.

**Comment by adamscarberry** [comment]
The few hours into the future is intentional.  If a user loads the UI at 10:00am, current the download modal will show the end date at 10:00am even if the current time is 10:15am.  It won't change to 10:15am unless the user refreshes the whole page.  Allowing the user to manually change a few hours into the future provides a little flexibility.

The CBRFC NBM fail is due to the package not able to transform that product.

Additional date picker adjustments can be made if needed.
