### ISSUE TITLE
[BUG REPORT]: rts-utils script error

### ISSUE THREAD

**Issue by ColbyCurtis** [USACE/cumulus#344]
When using the initialization script "rtsutils_init.py" I am getting this error on the first run, having copied and pasted the contents from the script provided at: https://github.com/USACE/rts-utils/wiki/Initialization-Script#rtsutils_initpy

![image](https://user-images.githubusercontent.com/119517002/226975002-fd4f245b-0a2f-4a15-a632-5012dc56e4ec.png)

Does anyone happen to know a fix for this?

**Comment by jeffsuperglide** [comment]
Closing due to no response to suggested solution.
