### ISSUE TITLE
[BUG REPORT]: LMRFC QPF

### ISSUE THREAD

**Issue by Scott-Chodkiewicz** [USACE/cumulus#345]
## Describe the bug
When looking at the available "products" for LMRFC QPF, data appears to be avilalbe through 4/1/23.  When attempting to download QPF grids from today (3/23/23), the page will not allow me to select a date in the future.  It grays out all available future dates as if no data is available to download.  

## Steps To Reproduce
I've attempted to download from various browsers and I get the same results.  I"ve also had others in the office attempt to download the LMRFC QPF for SAM and the Pascagoula Basin

## Expected behavior
When clicking on the download button, I'd expect to be able to select an end date in the future for QPF grids.  

## Actual behavior
When attempting to select an end date in the future, all dates are grayed out and can not be selected.  I've also attempted to manually enter a future date and it's not accepted in the dialog box.  

## Screenshots

see attached jpg for screen capture of the date selection screen which shows grayed out values.  
![LMRFC_QPF_Cumulus_Screencapture](https://user-images.githubusercontent.com/118551083/227315955-f590e039-8dfc-4682-8c28-65ac2e4d6e47.GIF)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Edge chrome and firefox

**Comment by jeffsuperglide** [comment]
@Scott-Chodkiewicz - Forecasts are versioned by date/time acquired.  Requesting a future date would be a request for a future forecast that isn't there.

**Comment by Scott-Chodkiewicz** [comment]
Jeff

In the past when downloading QPF 6 hours grids, I’ve been able to go 7 days into the future with my future date request.  Actually, I could arbitrarily select a date way out in the future and I’d only get available grids.  It sounds like that is no longer how QPF grids are handled through cumululs?  I’ve double checked with others in the office to make sure I was remembering this process correctly and everyone indicated they could select a future date (either 3-days our, or in the case of LMRFC as far out as 7 days).    When I couldn’t select a future date I thought I was seeing a bug so I didn’t even attempt to download the data, but when I tried to do so just now, I do see the grids go out into the future in the DSS file I download.


Scott Chodkiewicz
Hydraulic Engineer
U.S. Army Corps of Engineers - Mobile District
Office: (251) 690-3386
Cell: (251) 327-2390
Fax: (251) 694-4058
Email: ***@***.******@***.***>
Web: https://water.sam.usace.army.mil

From: Jeff Gregory ***@***.***>
Sent: Monday, March 27, 2023 11:28 AM
To: USACE/cumulus ***@***.***>
Cc: Chodkiewicz, Scott C CIV USARMY CESAM (USA) ***@***.***>; Mention ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [USACE/cumulus] [BUG REPORT]: LMRFC QPF (Issue #345)


@Scott-Chodkiewicz<Blockedhttps://github.com/Scott-Chodkiewicz> - Forecasts are versioned by date/time acquired. Requesting a future date would be a request for a future forecast that isn't there.

**Comment by jeffsuperglide** [comment]
@Scott-Chodkiewicz 

I don't remember all the details but the open ended time selection caused issue and confusion.  I'm sure things changing without notice can also be confusing but, remember, this application is in a testing environment and not in production.
