### ISSUE TITLE
[QA Review]: Investigate possible NAEFS http source

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#346]
We are currently getting `NAEFS MEAN QPF PRECIP 6hr` and `NAEFS MEAN QTF AIRTEMP 6hr` via LDM.

Any chance the following naefs products have that same data included?

https://www.nco.ncep.noaa.gov/pmb/products/naefs/

<img width="874" alt="image" src="https://user-images.githubusercontent.com/46494851/228693069-045a8af2-6459-4292-b2b9-cdf354581bcb.png">

https://nomads.ncep.noaa.gov/pub/data/nccf/com/naefs/prod/

**Comment by jeffsuperglide** [comment]
NAEFS file inventory does not list Precipitation as an available parameter.  All inventories from https://www.nco.ncep.noaa.gov/pmb/products/naefs/ were reviewed.

**Comment by adamscarberry** [comment]
thanks @jeffsuperglide  Closing as not a viable source.
