### ISSUE TITLE
NWS Southern Region - Investigate LDM Issues

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#348]
Please connect with South Region about the loss NAEFS data since last week and verify what maybe happening on their side.

**Comment by adamscarberry** [comment]
Data resumed 4/10/23

**Comment by jeffsuperglide** [comment]
NWS Regional HQ LDM POCs contacted via email asking status on LDM outage the beginning of April.  A representative from Eastern Region responded that their LDM DMZ was rebooted but failed to start.  No other notifications from the other regions.

EC2 LDM instance resumed connection to NWS Southern Region approx. 09Apr.  NAEFS products automatically acquired when connection established and product published.
