### ISSUE TITLE
[BUG REPORT]: ABRFC QPE Warping

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#350]
## Describe the bug
Projection differences between MRMS QPE and ABRFC QPE.  ABRFC QPE resulting DSS grid does not look like it is projected correctly.

## Expected behavior
Resulting DSS grid record should have the same/similar shape coming from different sources.

## Actual behavior
Tell us what actuall happened.

## Screenshots
<img width="935" alt="Screenshot 2023-04-26 at 2 19 09 PM" src="https://user-images.githubusercontent.com/37386268/234681508-f7b7a37d-66e0-42c3-8301-2134bc3442c2.png">

**Comment by adamscarberry** [comment]
@jeffsuperglide What should be done with all the productfiles already created and projected improperly?  There is no archive from the source, so replaying beyond a couple days is not possible.

**Comment by jeffsuperglide** [comment]
PR https://github.com/USACE/cumulus-geoproc/pull/42 closes this issue

**Comment by adamscarberry** [comment]
Next steps involve product file cleanup and potential re-processing:

- [ ] Delete bad productfiles from develop (database and S3) @adamscarberry 
- [ ] Delete bad productfiles from stable (database and S3) @adamscarberry 
- [ ] New Temporary DAG to reprocess the existing acquirablefiles @jeffsuperglide 
  - [ ] Process in develop (as a test) @jeffsuperglide 
  - [ ] Process in stable @jeffsuperglide

**Comment by jeffsuperglide** [comment]
Develop and Stable downloads of ABRFC and MRMS compared showing ABRFC projection issue solved.  Airflow re-notification DAG tested on Develop and then merged to Stable.  DAG run completed on both dev and stable.

Closing this issue.
