### ISSUE TITLE
[FEATURE REQUEST]: Communicate Product Ingest Status in UI

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#351]
Picking up from previous issue: https://github.com/USACE/cumulus/issues/258

Indicate in the UI that a product is beyond it's threshold since last product was processed.

**Comment by adamscarberry** [comment]
Proposal:  

![image](https://user-images.githubusercontent.com/46494851/235261759-02b4fbe8-6e9a-4043-ae19-0e80b46c904c.png)

![image](https://user-images.githubusercontent.com/46494851/235261796-654e9d2f-06f1-49fe-9974-590bd6b46801.png)

**Comment by adamscarberry** [comment]
@jeffsuperglide Can you review develop UI and let me know what you think?

**Comment by jeffsuperglide** [comment]
Changes in develop merged into stable

PR https://github.com/USACE/cumulus-ui/pull/158
