### ISSUE TITLE
[CHECKLIST]: SPK - Truckee watershed adjustment

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#354]
Follow-up for issue https://github.com/USACE/cumulus/issues/349

Received feedback on 5/17/23: 

> Sorry for the slow reply, yes everything is good except we have a new update for the Truckee watershed.  Could we get the Truckee clipped to the attached updated subbasin shapefile.

shapefile attached to email

**Comment by jeffsuperglide** [comment]
PR https://github.com/USACE/cumulus-api/pull/408 addresses this issue

**Comment by adamscarberry** [comment]
@jeffsuperglide Can you notify customer if not already done?
