### ISSUE TITLE
[BUG REPORT]: NAEFS AIRTEMP (QTF) Product Download Has The Wrong Data Type and Pathname

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#355]
# ToDo
- [x] Test locally
- [x] Merge ➡️  `develop`
- [ ] Merge `develop` ➡️  `stable`

NAEFS QTF (Forecast Temperature) Product should be INST-VAL data type with a DSS record pathname that has not E-Part.  

Currently it's coming out PER-CUM (as if Precip) and with a D- and E-Part:
![image](https://github.com/USACE/cumulus/assets/42588801/a998600c-127b-4298-aa59-7413db4c2259)

**Comment by adamscarberry** [comment]
Results of testing in develop after database fix:

<img width="1416" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/9d6d2ec5-5ed5-481d-ae31-c4424fc8a17f">
