### ISSUE TITLE
[BUG REPORT]: NBM AIRTEMP Products don't have consistent naming in the Cumulus Catalog and DSS Record Pathnames

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#356]
- [x] Test Local
- [x] Merge `branch` ➡️ `develop`
- [x] Merge `develop` ➡️ `stable`

Cumulus Catalog is missing the QTF label for the NBM 1hr product:
![image](https://github.com/USACE/cumulus/assets/42588801/3fbbee4e-c99e-4d80-9a85-0da3c2336cd4)

The 1HR NBM QTF is returning a DSS pathname with FPart:   NBM-QTF

The 3HR NBM QTF is returning a DSS pathname with FPart:   NBM

The 6HR NBM QTF is returning a DSS pathname with FPart:   NBM

**Comment by jeffsuperglide** [comment]
Tags:
<img width="460" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/eea33e60-2cc1-4cf8-9c19-4630cf1691e1">

Fpart:
<img width="164" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/6914273a-3b00-42c0-86a0-6a57aeeccc43">

**Comment by jeffsuperglide** [comment]
USACE/cumulus-api#422 closes this issue

Downloads:

<img width="465" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/b9504f7e-dcc5-431d-9907-b7af9501bd98">

DSS Fpart:

<img width="198" alt="image" src="https://github.com/USACE/cumulus/assets/37386268/3b5780ef-c8cb-4b1e-87ea-e83b0bacca6d">
