### ISSUE TITLE
[FEATURE REQUEST]: Missing MBRFC from Watershed Extents Option

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#357]
- [x] Test Local
- [x] Merge `branch` ➡️ `develop`
- [x] Merge `develop` ➡️ `stable`

As shown below, the MBRFC is missing from the download extents options in the watershed field for NOAA-NWS.

All RFC extents should have been provided before with their relevant extents.  But in case you can't find it, a place holder set of extents for MBRFC are included in the image below.

![image](https://github.com/USACE/cumulus/assets/42588801/e5f9bc2e-30e2-4005-afb9-3602d2787914)

**Comment by jeffsuperglide** [comment]
USACE/cumulus-api#422 closes this issue
