### ISSUE TITLE
[FEATURE REQUEST]: Add Watershed - NWDP - Columbia River

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#366]
From email request:
---

Hello Cumulus Team, 

I’d like to request an additional Office for Cumulus:

NWDP (Northwestern Division – Columbia River Water Management)

And an additional Watershed:

NWDP – Columbia River

(Our CWMS model covers the entire extents of the Columbia River basin, which includes NWP-Columbia River, NWS-Columbia River, and NWW-Columbia River)

 

I pulled these extents from our legacy grid processes:

columbia_basin:
```
  xmax: -1100000
  xmin: -2292000
  ymax: 3506000
  ymin: 2188000
 ```

And the grids have these values:
```
Lower Left Cell: (-1146, 1094)
Grid Extents: (597, 660)
Cell Size: 2000.0
```

 

Please let me know if you need anything else. Thanks in advance!

**Comment by adamscarberry** [comment]
Proposed watershed is the largest one.

<img width="936" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/f6f99cc6-ae23-478c-a4ba-622c47ddaec8">

**Comment by eric-y-chow** [comment]
Those extents look good, thank you!

**Comment by adamscarberry** [comment]
- [x] Deploy to Develop and verify
- [x] Deploy to Stable

Caching of offices/watersheds may prevent users from seeing the change right away.  May need to bump UI version for proper refresh.

**Comment by adamscarberry** [comment]
@eric-y-chow The `NWDP - Columbia River` watershed has been deployed.  Please test and verify.  If you are having trouble seeing it in the web interface, please do a hard refresh in browser.

Hard Refresh = press the Ctrl+F5 keys or, while holding down the Ctrl key, click on the Refresh button near the address bar. You can also use Ctrl+Shift and then press R.

**Comment by eric-y-chow** [comment]
Everything looks good! Tested a direct download from the cumulus site and also an extract from the CAVI. Thank you!

**Comment by adamscarberry** [comment]
Reopening to fix extents.  Extents provided did not cover shapefile.

<img width="901" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/d6ed989b-a573-4960-a7a7-087164a51f09">

Also needs more buffer at bottom and right, less on left.

<img width="696" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/56a1e85e-8bd8-4931-876d-eec736ead789">

**Comment by adamscarberry** [comment]
Going to use the following:

```
 xmax: -1090000
 xmin: -2180000
 ymax: 3517000
 ymin: 2178000
```

```sql
-- xmin,ymax (top left), xmax ymax (top right), xmax ymin (bottom right), xmin ymin (bottom left), xmin ymax (top left again)
UPDATE watershed 
	SET geometry = ST_GeomFromText('POLYGON ((-2180000 3517000, -1090000 3517000, -1090000 2178000, -2180000 2178000, -2180000 3517000))', 5070)
WHERE id = '8f150e1a-676b-4c63-b337-ec3e2c98cce3';
```

<img width="874" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/d73f1590-575f-4571-bf22-cdbe45b41c7b">

**Comment by eric-y-chow** [comment]
The new extents look good, thank you!

**Comment by adamscarberry** [comment]
- [x] deploy correction to develop
- [x] deploy correction to stable

**Comment by adamscarberry** [comment]
@eric-y-chow fix has been deployed, please verify.

**Comment by eric-y-chow** [comment]
It looks good! Here's my MetVue screenshot:
![image](https://github.com/USACE/cumulus/assets/100976025/08d4c7d9-394b-4cb1-bd36-6503d7841a9c)

**Comment by adamscarberry** [comment]
awesome.  thanks @eric-y-chow  for confirming.  closing issue

**Comment by adamscarberry** [comment]
cc @jeffsuperglide
