### ISSUE TITLE
[BUG REPORT]: Packager status hangs with no errors

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#368]
Originally reported via email by Brandon @jbkolze in LRL

> Good morning Cumulus folks, 
> 
> We seem to be having some sort of server-side processing issue with one of our normal gridded data downloads, specifically the MRMS-V12 QPE Pass 2 PRECIP 1hr product for the Little Miami River (LRL) watershed.  If I initiate a request for ~2 months of data (6/16/23-8/16/23), the processing progress updates continuously to around 75-80% and then stops without throwing any errors that I can see.  Just for testing purposes, I lengthened the request to ~2.5 months and the progress stopped at 62%.  I can run the same request for the Green River basin (which is significantly larger) successfully, so on the surface that seems to indicate that it’s not a lack-of-memory issue or something of the sort.  However, if I chop the request for the Little Miami into two ~1 month requests the processing/download completes successfully, so that seems to indicate that it’s not a “bad grid” causing issues either.
> 
>  Can you all look into what might be causing this?  We can work around it for the time being by chopping up our data requests, so it’s not extremely urgent, but it does somewhat disrupt our standard daily forecasting process so it would be nice to get it resolved if possible (or at least to confirm that it’s “unfixable” so that we can re-work our internal processes).
> 
> Let me know if there’s any more information I can provide that might be useful.
> 
> Thanks,
> Brandon

Tested a download in develop env using the following:

- Little Miami River (LRL) watershed.
- Date range of 6/16/23-8/16/23
- Product: MRMS-V12 QPE Pass 2 PRECIP 1hr

Logs do not indicate an error aside from a constant `munmap_chunk(): invalid pointer` which has been around for a while.

Memory Peaked at 96% before dropping to 2%.  This is when the download status of 86% stopped updating.

<img width="1719" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/efe13594-e53f-4fde-8c7d-5a8671474535">

Typically if the container crashes, it will show up as an event where a new container will replace it.  That did not happen leading me to believe a subprocess may be failing (out of memory maybe) and the parent process just continues without bubbling up the error.

**Comment by adamscarberry** [comment]
I'm starting to think there was a bad file (maybe more) in the time window above causing the error.  The below request was made for the same watersheds (2 months).  Assuming it's current time (9/6/23) minus 2 months:

![image](https://github.com/USACE/cumulus/assets/46494851/9f120f9d-0713-4ace-b45e-e13d93fc9f7c)

@jbkolze  can you confirm that this error no longer occurs with a 2 month window relative to today (now - 2months)?

**Comment by jeffsuperglide** [comment]
The program that writes GeoTiff data to DSS (tiffdss) is a cause of this issue.  A fix has been made to `tiffdss` to address errors when testing the GeoTiffs.  `tiffdss` is a C program that was not properly handling memory and trying to `free() an invalid pointer`.  That fix, along with some others, is in the latest version and was tested with the same data set.  All files wrote records to DSS successfully.

https://github.com/USACE/cumulus-api/tree/issue/368-invalid-pointer-packager

CC @adamscarberry

**Comment by adamscarberry** [comment]
Thanks @jeffsuperglide for the fix.

<img width="1791" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/9ece3bea-2c04-4351-a5db-8090c7192fef">


Download above used original product and time window.  Completed without hanging or errors.
