### ISSUE TITLE
[BUG REPORT]: SERFC QPE PRECIP 1hr Processing Incomplete, Unable to Download

### ISSUE THREAD

**Issue by DrewComan** [USACE/cumulus#374]
## Describe the bug
Trying to download SERFC QPE PRECIP 1hr for time window From: 2022-09-08 24:00  To: 2022-11-08 24:00  gets stuck at 31%. Have tried to download the same product and time window 3 times and all three times gets stuck at 31% complete in the Processing Time field and has not been able to download.

screen grab pasted below. thanks for your time and help!

![image](https://github.com/USACE/cumulus/assets/145124697/cf003b16-539e-43cf-aab4-8f27c6275025)

**Comment by adamscarberry** [comment]
Attempted this download (same product, watershed and time window) in develop environment.

Packager hung at 30% as indicated above (no errors from tifdss):

<img width="1196" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/309fcc7b-3205-4410-83a7-9f93ddb24073">


Container resources peaked at 67% CPU (maximum) and  89% Memory (maximum)

<img width="1153" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/43f6cfab-4a5d-4de2-9df9-946b65204c1c">

cc @jeffsuperglide

**Comment by adamscarberry** [comment]
Additional details:

- Changing the download to one month 8-Sep-22 - 8-Oct-22 also results in a 💥 failure at 60% complete.
- Changing the download to one month 8-Oct-22 - 8-Nov-22 also results in a 💥 failure at 60% complete.

**Comment by adamscarberry** [comment]
Using the same product and time window, but changing the watershed to a normal sized CWMS watershed (Tennessee & Cumberland River) resulted in a successful download.

<img width="1470" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/0590e72f-bb9d-401a-8013-e81985a8d6dd">

**Comment by adamscarberry** [comment]
- [x] fix deployed to develop, tested with original product, watershed, time window
- [x] fix deployed to stable, tested with original product, watershed, time window

**Comment by adamscarberry** [comment]
results:

![image](https://github.com/USACE/cumulus/assets/46494851/02ea3a1c-02a7-4df3-ac37-70f9384de263)


@DrewComan this should be fixed.  Please let us know if you run into anymore issues.

Thanks @jeffsuperglide for the fix.
