### ISSUE TITLE
[FEATURE REQUEST]: Add RFC Data Extents

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#378]
## Feature Request Type
- [x] ***User Interface (UI)***
- [X] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.
RFCs Areas of Responsibilities were originally added to Cumulus as summarized in the following issue:
https://github.com/USACE/cumulus/issues/277
and using the polygon shapefile from the following source:
https://www.weather.gov/gis/RFCBounds

However, the RFC data extents are actually beyond the Areas of Responsibilities polygons as shown in the following image:
![image](https://github.com/USACE/cumulus/assets/42588801/ddb68c7d-7844-47c5-b653-bdd4e551cfec)

The actual RFC data extents are really useful for Cumulus downloads to see approaching weather systems.

## Describe the solution you'd like
Suggest renaming the currently implemented RFC download extents in Cumulus to "NOAA-NWS-RFC-AOR", i.e. Area of Responsibility.

Then please add the attached RFC data extents as a new download extents option called "NOAA-NWS-RFC"
[RFC_Extents.zip](https://github.com/USACE/cumulus/files/12886117/RFC_Extents.zip)

![image](https://github.com/USACE/cumulus/assets/42588801/0559b56d-e55d-43ce-a952-19a4de27d4d6)

**Comment by adamscarberry** [comment]
@FHanbali Is there a point to having both sets of extents?  If we really just use RFC extents to test RFC products, we should modify the existing RFC watersheds already in Cumulus...agree?

**Comment by FHanbali** [comment]
That's fine @adamscarberry , would be better to have only the full data extents from each RFC.   And there is the flexibility for for folks to get more clipped extents to their desired watersheds, and hopefully soon using user-specified shapefiles.

**Comment by adamscarberry** [comment]
New extents below for migration.

## ABRFC
xmin = -970000
xmax = 471700
ymin = 1035600
ymax = 1880000

## APRFC
**New watershed not already in Cumulus**
xmin = -3310000
xmax = -1840000
ymin = 3969900
ymax = 6108000

## CBRFC
xmin = -1992000
xmax = -486000
ymin = 894000
ymax = 2522000

## CNRFC
xmin = -2452000
xmax = -1404000
ymin = 1134000
ymax = 2684000

## LMRFC
xmin = -282000
xmax = 1706000
ymin = 326200
ymax = 2322000

## MARFC
xmin = 1087500
xmax = 2138600
ymin = 1505800
ymax = 2570200

## MBRFC
xmin = -1468000
xmax = 793300
ymin = 1464900
ymax = 3115900

## NCRFC
xmin = -836562
xmax = 1351600
ymin = 1381207
ymax = 3206311

## NERFC
xmin = 1300000
xmax = 2374100
ymin = 1996000
ymax = 3222000

## NWRFC
xmin = -2404000
xmax = -950000
ymin = 2010200
ymax = 3595900

## OHRFC
xmin = 531800
xmax = 1603000
ymin = 1292700
ymax = 2530500

## SERFC
xmin = 447000
xmax = 2124600
ymin = 173800
ymax = 2068300

## WGRFC
xmin = -1333700
xmax = 505300
ymin = 102800
ymax = 1810800

**Comment by adamscarberry** [comment]
Example update for MARFC:

Before:
![image](https://github.com/USACE/cumulus/assets/46494851/d6e3faf9-a05e-4fa3-8985-eeda940f2d4f)


After:
![image](https://github.com/USACE/cumulus/assets/46494851/6539aef7-cc8d-4627-93cf-7668cfadc6cd)

**Comment by adamscarberry** [comment]
- [x] deploy to develop
- [x] deploy to stable

**Comment by adamscarberry** [comment]
completed and deployed
