### ISSUE TITLE
SERFC DATA Request

### ISSUE THREAD

**Issue by cddonald22** [USACE/cumulus#383]
Is there any to get QPE Cumulus data for SERFC from May 2021 through July 2021?

The current available data is from August 2021.

**Comment by adamscarberry** [comment]
@cddonald22 SERFC QPE is acquired from this web source: https://tgftp.nws.noaa.gov/data/rfc/serfc/misc/

We started the acquisition in August 2021 and the source above does not provide a long term historical data set.

Currently this is not possible.

related to https://github.com/USACE/cumulus/issues/325
