### ISSUE TITLE
[BUG REPORT]: WRF-Columbia Precip 1hr: No Data within Downloaded DSS File

### ISSUE THREAD

**Issue by junixon** [USACE/cumulus#387]
## Describe the bug

I’ve attempted to download hourly precipitation WRF as a DSS file from Cumulus version 1.4.4. Unfortunately the downloaded data is empty. According to Cumulus, WRF data is available during Water Year 1969.
 
 
I Created DSS Download for WRF hourly precip, covering the watershed NOAA-NWS Southeast River Forecast Center (SERFC), during time window Aug-October 1969,  as shown in the figure below
 
After submitting the download request, the supposed WRF appears as a DSS file in my computer’s download folder, as shown below: 
 
However, the DSS file does not appear to contain any data, as shown in screenshot of HEC-DSSVue below:
 

I’ve attempted to download hourly precipitation WRF as a DSS file from Cumulus version 1.4.4. Unfortunately the downloaded data is empty. According to Cumulus, WRF data is available during Water Year 1969.
 
![image](https://github.com/USACE/cumulus/assets/71674772/17c59950-b03c-4c9c-9988-7eb1f83737ca)
 
I Created DSS Download for WRF hourly precip, covering the watershed NOAA-NWS Southeast River Forecast Center (SERFC), during time window Aug-October 1969,  as shown in the figure below
 
![image](https://github.com/USACE/cumulus/assets/71674772/bfbadadd-53cb-4f7b-a22c-bc5b5e80e2ca)

After submitting the download request, the supposed WRF appears as a DSS file in my computer’s download folder, as shown below: 
 
![image](https://github.com/USACE/cumulus/assets/71674772/2a5959b1-15b2-4b6a-9b26-23fca410048b)

However, the DSS file does not appear to contain any data, as shown in screenshot of HEC-DSSVue below:
 
![image](https://github.com/USACE/cumulus/assets/71674772/af3477cf-ad49-4da8-b929-138ccdb7bda9)

## Desktop (please complete the following information):
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by adamscarberry** [comment]
@junixon This data set is for the Columbia River Basin.  I would only expect data to be present in the north west of the U.S.

Example:  WRF Columbia with NWRFC watershed extents: https://cumulus-api.corps.cloud/cumulus/download/dss7/download_e452225f-b84b-434d-9c7c-d5d30a3bcd33.dss

<img width="1412" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/349b2384-13bc-4597-b55e-2c2f120f6668">
