### ISSUE TITLE
[FEATURE REQUEST]:Need updated extents for SPN's Alameda Watershed

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#389]
## Feature Request Type
- [ ] ***User Interface (UI)***
- [X] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.
Current extents in Cumulus don't cover the entire watershed (see attached image)
![AlamedaCreekWatershed](https://github.com/USACE/cumulus/assets/42588801/3285d25b-ba9a-4261-b42b-880d7a8ed585)

## Describe the solution you'd like
Please updates extents using the following shapefile.
https://drive.hecdev.net/share/zL-oEA6l

**Comment by FHanbali** [comment]
[Uploading SPN_AlamedaMap.zip…]()

**Comment by adamscarberry** [comment]
fix deployed to develop and stable

<img width="798" alt="image" src="https://github.com/USACE/cumulus/assets/46494851/44ff5854-d4b3-4645-9222-2b7f312017c1">
