### ISSUE TITLE
[PRODUCT]: MVP-Eau Galle Extents

### ISSUE THREAD

**Issue by Emily-Moe** [USACE/cumulus#408]
## Product Source (URL Preferred)
All
## Product Description
Extents of MVP-Eau Galle watershed do not cover the full CWMS basin footprint. Requesting extents be updated to cover the attached watershed shapefile.
![image](https://github.com/USACE/cumulus/assets/168835450/105de981-b06c-4375-b931-be0b95dffcc9)
[hmsBasinsEauGalle.zip](https://github.com/USACE/cumulus/files/15200353/hmsBasinsEauGalle.zip)

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [ ] NetCDF
- [ ] Other (Please provide description below)

**Comment by adamscarberry** [comment]
Hey @msweier thanks for handling this fix.  Can we close this issue?

**Comment by msweier** [comment]
You bet!
