### ISSUE TITLE
[PRODUCT]: Additional Florida Extents map

### ISSUE THREAD

**Issue by katfeingold** [USACE/cumulus#411]
## Product Source (URL Preferred)
Extent Addition for the state of Florida - SAJ would like this added as an option for extents in Cumulus

## Product Description
[FloridaExtents.zip](https://github.com/user-attachments/files/15794777/FloridaExtents.zip)

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [ ] NetCDF
- [X ] Other (Please provide description below)

#### Format Description

Shapefile

**Comment by adamscarberry** [comment]
Hey @katfeingold, I wanted to give you an assist on this watershed add.

Here's the sql that you will need to add as a new migration:

```sql
--(xmin ymax, xmax ymax, xmax ymin, xmin ymin, xmin ymax)

-- notes
/**********************
Buffered extends from qgis

xmin = 989539.3071116814
xmax = 1671778.6007457851
ymax = 978696.9156769654
ymin = 385612.5100058009

After rounding by hand

xmin = 989500
xmax = 1671800
ymax = 978700
ymin = 340000

*********************/

-- add new watershed
INSERT INTO watershed (id, slug, "name", geometry, office_id, output_srid) VALUES
	 ('bfbd5b34-ff07-41d4-87cf-d67c80f98be1','florida','Florida',ST_GeomFromText('POLYGON ((989500 978700, 1671800 978700, 1671800 340000, 989500 340000, 989500 978700))',5070),'4142c26c-0407-41ad-b660-8657ddb2be69', 5070);
```

This should provide the following coverage:

![image](https://github.com/user-attachments/assets/27f32fb2-c4e2-46d5-84b8-a1f4f1c64b27)

@Enovotny should be able to help with any further technical details.

**Comment by adamscarberry** [comment]
<img width="607" alt="image" src="https://github.com/user-attachments/assets/de951c82-311c-449b-94da-9a902d258a4b">
