### ISSUE TITLE
[Watershed Extents]: NWP Request for Crooked River

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#418]
Request for Crooked River extents update.

**Comment by jeffsuperglide** [comment]
[Subbasins.zip](https://github.com/user-attachments/files/16617760/Subbasins.zip)

**Comment by adamscarberry** [comment]
deployed to stable here: https://github.com/USACE/cumulus-api/pull/498

**Comment by adamscarberry** [comment]
> Hi all, thank you for updating the grid extents. The QPE and QTE look great. However, the QTF and QPF are still missing a small portion of the grid extent. Would someone be able to extend it the rest of the way? Thank you!
> 
> Best,
> Sammy C (NWP)

![image](https://github.com/user-attachments/assets/a0c53486-fb98-41e4-892a-222e21cb5a6f)

**Comment by adamscarberry** [comment]
I just checked the extents locally with the shapefile provided:

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/caab3e4a-a860-49b9-b4b0-1710fe64b320">

**Comment by adamscarberry** [comment]
Top Area (no buffer, but still covers)

<img width="1176" alt="image" src="https://github.com/user-attachments/assets/f967635a-42d1-4626-944c-57349ff46985">

Bottom:

<img width="2089" alt="image" src="https://github.com/user-attachments/assets/801619e3-fe55-4b27-8e57-e860a7151588">

**Comment by adamscarberry** [comment]
@katfeingold Can you follow up with Sammy.  You were CC'ed on that last communication.
