### ISSUE TITLE
[FEATURE REQUEST]: Cuyama River Watershed Cumulus Grid Definition

### ISSUE THREAD

**Issue by jeffsuperglide** [USACE/cumulus#422]
## Feature Request Type
- [ ] ***Application Programming Interface (API)***

## Is your feature request related to a problem? Please describe.
Cumulus grid definition appears to be out of sync with the watershed (see graphic below) for the Cuyama River watershed.

## Describe the solution you'd like
Adjust the Cumulus setup to include all of the watershed

## Describe alternatives you've considered
N/A

## Additional context
![image](https://github.com/user-attachments/assets/3ceb8a4e-b7f7-4c36-8350-666922c2e95d)

[Cuyama Subbasin shaptfiles.zip](https://github.com/user-attachments/files/16626299/Cuyama.Subbasin.shaptfiles.zip)

**Comment by jeffsuperglide** [comment]
Email request from kenneth.e.lawler@usace.army.mil

>  Hi,
>
> I am following up on this request to get the Cumulus grid definition fixed for the Cuyama River Basin. It has been over four weeks since my request. I have not heard back and the problem still exists. I am trying to troubleshoot this model and need to get the correct watershed definition set up in Cumulus. I’ve attached the correct watershed outline.
>  
> Can you help me? Do I have the right email address?
>  
> Ken

**Comment by katfeingold** [comment]
Merged to stable and contacted Ken letting him know it was updated.  Closing issues.
