### ISSUE TITLE
[BUG REPORT]: Slower than usual Cumulus data processing in the last week

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#426]
The LRD division office is reporting slower than usual processing of a data request on the Cumulus server side.   Have there been an issues with Cumulus in the last week or so that may have affected data processing performance?

**Comment by adamscarberry** [comment]
I can see the slowness.  Enabling performance insights on the RDS instance has shown some top queries causing issues.

One of the top ones was coming from the Prometheus metrics (scraping) service.  Those metrics haven't displayed correctly for a while in grafana.  I turned that service off to see how performance improves.

![image](https://github.com/user-attachments/assets/58880c98-0eb8-4a21-8061-1e12f95f6be8)


I could notice the products page in the web UI loaded much faster than before.

I'll continue to monitor.

**Comment by adamscarberry** [comment]
![image](https://github.com/user-attachments/assets/d234936e-2130-4a7c-89b2-776a37ce95a7)

**Comment by adamscarberry** [comment]
![image](https://github.com/user-attachments/assets/cca3ccff-4df4-4502-a8b8-e8dcf01c72f3)

![image](https://github.com/user-attachments/assets/e919f113-d17a-4ff3-b69b-d37f34297cf8)

![image](https://github.com/user-attachments/assets/babbcbb2-2a69-4c23-a6e2-dfb97e46f6c7)

**Comment by adamscarberry** [comment]
As of 9/17/24 @ 7:25am

![image](https://github.com/user-attachments/assets/fd1ba60d-692d-4e95-8293-f2360813f2e3)

**Comment by adamscarberry** [comment]
As of 9/1724 @ noon eastern:

![image](https://github.com/user-attachments/assets/3f6187fb-b82a-4c09-bf48-a35db8ee4bd8)
