### ISSUE TITLE
[CHECKLIST]:Renew Keycloak LetsEncrypt Cert in corps.cloud account

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#432]
This is the current auth server for Cumulus as of 11/4/2024

Had issues renewing the certs on Mac with the always on VPN setting.  Had to submit a ticket with RDE Helpdesk to allow it to be disabled long enough to create the new certs on my Mac (it uses dns port 53 which is blocked while on VPN).

Renew:

- [x] develop-auth.corps.cloud
- [x] auth.corps.cloud

These certs expire on 2/2/25

**Comment by adamscarberry** [comment]
CC @jeffsuperglide @willbreitkreutz

**Comment by willbreitkreutz** [comment]
@adamscarberry thanks for doing that
