### ISSUE TITLE
SNODAS UNMASKED Interpolated Products; Process Historic Archive 2010 - Present

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#55]
Can be processed using the new `cumulus-geoprocess` container.  Should be done by sending SQS messages to SQS queue `cumulus-geoprocess`. Message format can be found here https://github.com/USACE/cumulus-api/blob/develop/utils/geoprocess-message.py#L11

**Comment by adamscarberry** [comment]
snodas interpolated processing is now enabled for realtime.  Archive processing in progress.

@brettpalmberg  @FHanbali

**Comment by brettpalmberg** [comment]
Awesome!  Thanks @adamscarberry

**Comment by adamscarberry** [comment]
interpolated processing completed back to available archive (Feb 2010)
