### ISSUE TITLE
PRISM Stable Geoprocessor

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#59]
* tmin (minimum temperature)
* tmax (maximum temperature)
* ppt (precipitation)

**Comment by brettpalmberg** [comment]
Data acquisition is complete via Airflow.  @jeffsuperglide , can you take a look at the async-geoprocess processor that would be required for this product?

**Comment by adamscarberry** [comment]
- [ ] New DAG created
  - [ ] Deployed to develop
  - [ ] Deployed to stable

- [ ] New Acquirables added to db migration, New Products added to db migration
  - [ ] Deployed to Develop
  - [ ] Deployed to Stable
- [ ] Suite name changed / product labels changed to include early/stable

**Comment by brettpalmberg** [comment]
Awaiting:
* Deployment of scale-out version of Airflow (USACE/cumulus#215)
* `develop` --> `stable` merge of Cumulus API (USACE/cumulus-api#284)

**Comment by brettpalmberg** [comment]
@adamscarberry, you got it from here!

**Comment by adamscarberry** [comment]
Waiting on stable airflow re-deploy by @brettpalmberg  to work out bugs with airflow causing the PRISM stable backloading to fail half the time.  Issues with S3 reading or writing as well.

**Comment by brettpalmberg** [comment]
> Waiting on stable airflow re-deploy

In progress now.  Hoping this will be complete and stable by this afternoon 🤞

**Comment by adamscarberry** [comment]
Airflow is backfilling now 👍
