### ISSUE TITLE
User Interface: Catalog Redesign

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#61]

**Comment by adamscarberry** [comment]
Proposed changes to catalog page:  Before & After

![image](https://user-images.githubusercontent.com/46494851/112524406-287efb80-8d76-11eb-9447-9243fc76bffe.png)

**Comment by FHanbali** [comment]
> Proposed changes to catalog page: Before & After
> 
> ![image](https://user-images.githubusercontent.com/46494851/112524406-287efb80-8d76-11eb-9447-9243fc76bffe.png)

Looks great. Thx Adam!
