### ISSUE TITLE
Productfile constraint not working on null field

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#69]
235 records in the productfile table have one or more duplicates.

- Remove duplicates from database
- update records where **version** is null by setting **version** = '1111-11-11T11:11:11.11Z'
-  apply DEFAULT value to **version** of '1111-11-11T11:11:11.11Z'
- apply NOT NULL to **version**

**Comment by adamscarberry** [comment]
Resolved in AWS DB.  Seed data will be fixed when @brettpalmberg  merges feature/geoprocess-worker-container with develop.

**Comment by brettpalmberg** [comment]
Merged `feature/geoprocess-worker-container`: https://github.com/USACE/cumulus-api/pull/70
