### ISSUE TITLE
Investigate Alaska Data Coverage for Existing Products

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#72]

**Comment by brettpalmberg** [comment]
The NCEP Stage IV Mosaic 1hr, 6hr, 24hr products are produced for Alaska. These grids are not being downloaded at present, but sit adjacent to where the CONUS Stage IV grids are being acquired right now.

**Comment by willbreitkreutz** [comment]
Not worth the effort to support AK until someone from that region provides all the relevent details (projections etc...)
