### ISSUE TITLE
Packager - Support Processing to DSS in Multiple Coordinate Systems

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#73]
This will support creating DSS Grids for areas outside of CONUS. For Example, Alaska

* Consider storing default coordinate reference system on `watershed` entity in the database. To be used by `Packager` when creating DSS files.

**Comment by jeffsuperglide** [comment]
C program tiffdss setup to generate SHG or HRAP.  UTM can be added.  Moving fixed parameters like xResolution, yResolution, Spacial Reference etc to the payload can help being more dynamic.  Tar gzip packager plug-in ready to be incorporated and can take advantage of the same parameter move to payload.

**Comment by brettpalmberg** [comment]
Awesome @jeffsuperglide! Is there a PR that we can link here w/ the relevant code changes for review?

**Comment by jeffsuperglide** [comment]
@adamscarberry reviewing and found issues.  Working through those now.

**Comment by jeffsuperglide** [comment]
## Example JSON:

### Grid Types `tiffdss` recognizes:

- shg and shg-time (ALBERS = 420)
- hrap and hrap-time (HRAP = 410)

_the following have not been implemented_
- utm and utm-time (SPECIFIED_GRID_TYPE = 430) _need to confirm this type_
- wkt and wkt-time (SPECIFIED_GRID_TYPE = 430) _need to confirm this type_
- ? (UNDEFINED_GRID_TYPE = 400)

### Notes

- lat/long can be used to determine hemisphere and UTM zone
- need to get with Karl about DSS7 and WKT for the SRS Definition and Grid Type
- `-time` defines grid struct `_isTimeStamped`, which is (boolean) false for data that is time-invariant (e.g. grids of stable parameters, like ground elevation)
- `tiffdss` determines a DSS record as `_isInterval` (false for instantaneous values, true for period data) using the DSS epart
- if `writer` attribute `name` not a DSS writer, `grid_type` can be None
- `writer` attribute `format` can be None, default is `GTiff` driver
- DSS Apart from `grid_type`
- DSS Bpart from `extent` attribute `name`

```
{
    "download_id": "cf080263-8467-4607-8f34-995cc9880443",
    "bucket": "castle-data-develop",
    "key": "cumulus/download/dss7/download_cf080263-8467-4607-8f34-995cc9880443.dss",
    "writer": {
        "name": "dss7",
        "dst_srs": "EPSG:5070",
        "grid_type": "shg-time",
        "xRes": 2000,
        "yRes": 2000,
        "format": "GTiff"
    },
    "extent": {
        "name": "Columbia River",
        "latitude": 36,
        "longitude": -86,
        "bbox": [
            -2144000,
            2522000,
            -1694000,
            2920000
        ]
    },
    "content": [
        {
            "bucket": "castle-data-develop",
            "key": "cumulus/products/cbrfc-mpe/xmrg0606202220z.tif",
            "src_srs": "EPSG:4326",
            "dss_datatype": "PER-CUM",
            "dss_cpart": "PRECIP",
            "dss_dpart": "06JUN2022:1900",
            "dss_epart": "06JUN2022:2000",
            "dss_fpart": "CBRFC-MPE",
            "dss_unit": "MM"
        },
        {
            "bucket": "castle-data-develop",
            "key": "cumulus/products/cbrfc-mpe/xmrg0606202220z.tif",
            "src_srs": "EPSG:4326",
            "dss_datatype": "PER-CUM",
            "dss_cpart": "PRECIP",
            "dss_dpart": "06JUN2022:2100",
            "dss_epart": "06JUN2022:2200",
            "dss_fpart": "CBRFC-MPE",
            "dss_unit": "MM"
        }
    ]
}
```
