### ISSUE TITLE
Move Responsibility for Creating Geoprocessing Messages from Airflow --> Cumulus Database

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#74]
* Store a record of all raw files in the database.  Entity will be called `acquirable_file` or similar.
    * Requires database table design
    * Requires API Endpoints for `acquirable_files`
* Implement POST endpoint for `acquirable_files`.  This will allow airflow to save record of new `acquirable_file` to the database via the cumulus API.
* Trigger geoprocessing of `acquirable_file` (raw file) --> `productifile` (cloud optimized geotiff) using Postgres [LISTEN/NOTIFY](https://www.postgresql.org/docs/9.1/sql-notify.html) .  The LISTEN will be handled in the container [async_listener](https://github.com/USACE/cumulus-api/blob/develop/async_listener/listener/main.go).

* Implement POST endpoint for `productfiles`. This will allow `async_geoprocess` to save record of new files to the database via the API rather than through a direct database connection once geoprocessing is complete

Additional details and diagrams to follow.

**Comment by adamscarberry** [comment]
Remember to address the not null constraint mentioned in USACE/Cumulus#71

**Comment by adamscarberry** [comment]
Database tables changes have been merged in for local testing.  Changes also made to dev database.
