### ISSUE TITLE
API: Add Product Description field to database and API

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#79]
based on changed proposed by @jeffsuperglide  in branch "feature/productDescription".  This branch can now be deleted.

**Comment by adamscarberry** [comment]
accidentally pushed to develop, so there is no linked pull request.  Changes are ready for the API container to be restarted. @brettpalmberg

**Comment by brettpalmberg** [comment]
All good 😄 . Thanks for the heads-up

**Comment by adamscarberry** [comment]
new column added to dev database.
