### ISSUE TITLE
News Feed / Blog Concept

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#80]
* New Product Added, analysis on existing product, etc.
* Operational notices for Cumulus service
* Etc

**Comment by adamscarberry** [comment]
I like this design concept for blog/news feed: 
![image](https://user-images.githubusercontent.com/46494851/120574637-b2d68200-c3ed-11eb-951c-d32fd114fb76.png)

**Comment by brettpalmberg** [comment]
Totally agree!  I really like this design concept too.

**Comment by willbreitkreutz** [comment]
Closing since we implemented this on the home page.
