### ISSUE TITLE
Cumulus Request Fulfillment Levels-of-Service

### ISSUE THREAD

**Issue by FHanbali** [USACE/cumulus#81]
It would be great to have a simple section on data requests (maybe include this in the contacts page) to provide an idea on expected turnaround time for different levels of effort involved to fulfill different data requests, such as for new data products or archives of historic data not yet available on Cumulus, etc.

Also, be clear please that data service requests are meant for the Corps only, although available data access is meant to be public.

**Comment by brettpalmberg** [comment]
Hey @FHanbali - thank you. Reviewing all of our GH Issues and came to this one. We have been tracking new product requests via Github Issues, which seems to be working well. We recently added a custom Issue template (you'll see 'Product' is one of the new issue types that an be opened).

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/29417036/183192598-f39f1462-19ac-440f-a3d9-f252df37452c.png">

Here's an example of a product request for the NCEP Stage IV Precipitation mosaic: #255

This seems to meet the intent of this proposed feature, without the added effort and associated long-term maintenance of adding this capability to the webapp, cumulus-api, and database schema.

Closing this issue at this time, but we can revisit the topic in the future if we've missed something.
