### ISSUE TITLE
[CPC Support]: Green River extents do not cover watershed correctly

### ISSUE THREAD

**Issue by adamscarberry** [USACE/cumulus#87]
![image](https://user-images.githubusercontent.com/46494851/113715657-c13b4280-96b7-11eb-8b37-5167fac42d82.png)

**Comment by adamscarberry** [comment]
Emailed user with sample data set from Cumulus to see if extents were correct.  If correct, I'll set CPC to match Cumulus.  Otherwise I'll need to get the shapefile.

**Comment by brettpalmberg** [comment]
cc @FHanbali - FYI - we're using the tag `support` to categorize issues as user/field support.  Thanks @adamscarberry !

**Comment by adamscarberry** [comment]
User confirmed Cumulus extents were good.  CPC values for NWDP's Green River have been set to Cumulus' Green River extents.  Closing issue.
